### ISSUE TITLE
Candle open exact same as candle close on Forex data

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [ranaroussi/yfinance#1075] opened 2022-10-04 14:13 UTC
I noticed that in the last months of daily forex candles, open prices are the same than close prices. This cannot be true because I compared with other sources like tradingview and candle open are definitely not the same as close.
```
import yfinance as yf
import pandas as pd
ticker = 'EURUSD=X'
start_date = '2010-01-01'
end_date = '2022-10-02'

period = '730h'
interval = '1d'
forex_data = yf.download(ticker, start=start_date, end=end_date, interval=interval)
forex_data.index = pd.to_datetime(forex_data.index)

# count occurrences of open == close
forex_data[forex_data['Open'] == forex_data['Close']].index.year.value_counts()
```

```
2022    139
2012    121
2013     54
2016     44
2014     34
2015     23
2019     20
2011     18
2018     18
2021     15
2020     13
2017     11
2010      6
Name: Date, dtype: int64
```

**Comment by Karlheinzniebuhr** [comment] 2022-10-04 16:46
This is an issue of yahoo_finance itself, please like & retweet so this gets attention 
https://twitter.com/playratewinrate/status/1577336404891377665?s=20&t=VH94h-5zcUsy75LmlE4KAQ  
![FePSw4SXwAIB145](https://user-images.githubusercontent.com/5278928/193878575-b00b11ab-5125-411f-a7d6-c9eb815bc785.jpg)

**Comment by ValueRaider** [comment] 2022-10-27 21:23
Duplicate of #1071

**Closed by ValueRaider** 2022-10-27 21:23 UTC
Labels: Yahoo database
