### ISSUE TITLE
Possibility to fetch live market history (facing ~90s lag)

### ISSUE THREAD

**Issue by trueToastedCode** [ranaroussi/yfinance#1225] opened 2022-12-05 19:00 UTC
**Describe the problem**
Here is a method, that fetches until a. certain close with a 5 min interval.
```
def get_latest_data(target_datetime, interval='5m', timeout_s=240,
                    t_delta_past=timedelta(hours=4), t_delta_future=timedelta(minutes=1),
                    cooldown_s=0.5):
    t_start = time.time()
    while time.time() - t_start < timeout_s:
        df = ticker.history(interval=interval,
                            start=target_datetime - t_delta_past,
                            end=target_datetime + t_delta_future)
        if not df[df.index == target_datetime].empty:
            return df
        time.sleep(cooldown_s)
    raise TimeoutError

target_close = datetime.strptime('2022-12-05 18:45:00+00:00', '%Y-%m-%d %H:%M:%S%z')
df = get_latest_data(target_close)
print(df.iloc[-1])
```
In order to get to that specific datetime, the method will add another minute so that the api includes the latest row... and not ends  the data there.

I noticed, that with this code, in the first ~90s the latest row in the fetched history is actually not a 5 min close (although I set the interval ti '5m'). Instead it is 1 or 2 minutes before (not even a valid entry for that 5 min interval).

Only when waiting ~90s, the expected latest row for the provided time occurs.

When working with the live market, a 90s gap is a huge problem.

**Describe the solution**
1. The history should not include data, from another interval when it was being asked tu use 5 min or whatever
2. There should be no delay

**Additional context**
I am trying to work with the live market and fetch the history, directly after eg. the latest 5 min close.

**Comment by ValueRaider** [comment] 2022-12-05 20:44
This should be fixed in `dev` branch. We need to wrap up some changes to financials handling then can pump out a release.

**Comment by trueToastedCode** [comment] 2022-12-05 21:14
> This should be fixed in `dev` branch. We need to wrap up some changes to financials handling then can pump out a release.

That's good to hear... just switched to the dev branch. The issues, that they're invalid data, I can confirm has been fixed. However there is still a ~90s gap until its possible to fetch the latest data :/ prob this just is a limitation with yahoo finance.

**Comment by ValueRaider** [comment] 2022-12-06 16:56
What version exactly are you using? I noticed a delay bug introduced in 0.2.0rc2 although not constant 90s because caused by caching web request. When I fix this I can't reproduce any delay problem (ticker "INTC").

**Comment by ValueRaider** [comment] 2023-02-02 18:50
What is current status of this bug? Fixed?

**Closed** 2023-04-11 20:01 UTC
