### ISSUE TITLE
pandas 'unit' deprecation warning 

### ISSUE THREAD

**Issue by microprediction** [ranaroussi/yfinance#1853] opened 2024-02-08 00:08 UTC
yfinance/utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_t
imedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')

**Comment by Rational-IM** [comment] 2024-02-08 20:58
I confirm that this warning is happening. I'm getting exactly the same warning after an update to my IDE/Pythons/libraries.

**Comment by richardmfrank** [comment] 2024-02-11 14:43
Same here.  Warning started after updating Pandas from 2.1.1 to 2.2.0

**Comment by ValueRaider** [comment] 2024-02-11 15:32
How to contribute #1084

**Comment by ValueRaider** [comment] 2024-02-17 11:53
Duplicate of #1837

**Closed by ValueRaider** 2024-02-17 11:53 UTC

**Comment by wahid18-maqs** [comment] 2024-03-27 11:10
having same issuses

**Comment by tantedeval** [comment] 2024-06-30 14:12
The problem might be fixed by upgrading yfinance to version 0.2.40.
I received the exactly same message while I was using version 0.2.28.

Plus, even I received the warnings, it does not effect the result of the downloading.

I looked into the packages of pandas and yfinance, and I think the func [fix_Yahoo_dst_issue] is meant to cope with the issue therefore sending a message meanwhile.(I just my interpertation. I didn't go deep. Correct me if anyone should find me wrong.)

Last, has anyone tried degrade pandas, see how o it works out?

<img width="1279" alt="微信图片_20240630220153" src="https://github.com/ranaroussi/yfinance/assets/135407563/415bb2fa-f210-413b-8ce2-174b327f66bf">
<img width="1279" alt="微信图片_20240630220240" src="https://github.com/ranaroussi/yfinance/assets/135407563/57b29ba9-e913-425a-8376-0e73f9cf9452">

**Comment by ValueRaider** [comment] 2024-06-30 14:36
@wahid18-maqs  create new issue, follow instructions
