### ISSUE TITLE
regularMarketPrice removed for Index

### ISSUE THREAD

**Issue by hkbb2014** [ranaroussi/yfinance#1530] opened 2023-05-18 02:33 UTC
I used to use the following code to read index current price, but it does not work recently. The key 'regularMarketPrice' is not available anymore. Any alternative to regularMarketPrice?

stock_info = yf.Ticker('^DJI')
currentPrice = stock_info.info['regularMarketPrice']

# now the dictionary is
dict_keys(['maxAge', 'priceHint', 'previousClose', 'open', 'dayLow', 'dayHigh', 'regularMarketPreviousClose', 'regularMarketOpen', 'regularMarketDayLow', 'regularMarketDayHigh', 'volume', 'regularMarketVolume', 'averageVolume', 'averageVolume10days', 'averageDailyVolume10Day', 'bid', 'ask', 'bidSize', 'askSize', 'fiftyTwoWeekLow', 'fiftyTwoWeekHigh', 'fiftyDayAverage', 'twoHundredDayAverage', 'currency', 'exchange', 'quoteType', 'symbol', 'underlyingSymbol', 'shortName', 'longName', 'firstTradeDateEpochUtc', 'timeZoneFullName', 'timeZoneShortName', 'uuid', 'messageBoardId', 'gmtOffSetMilliseconds', 'trailingPegRatio'])

# here is the key, value returned, but I cannot find the current market price.

maxAge: 86400
priceHint: 2
previousClose: 33012.14
open: 33092.48
dayLow: 33050.41
dayHigh: 33472.38
regularMarketPreviousClose: 33012.14
regularMarketOpen: 33092.48
regularMarketDayLow: 33050.41
regularMarketDayHigh: 33472.38
volume: 310712570
regularMarketVolume: 310712570
averageVolume: 305899672
averageVolume10days: 265471000
averageDailyVolume10Day: 265471000
bid: 33366.72
ask: 33450.49
bidSize: 0
askSize: 0
fiftyTwoWeekLow: 28660.94
fiftyTwoWeekHigh: 34712.28
fiftyDayAverage: 33154.523
twoHundredDayAverage: 32762.293
currency: USD
exchange: DJI
quoteType: INDEX
symbol: ^DJI
underlyingSymbol: ^DJI
shortName: Dow Jones Industrial Average
longName: Dow Jones Industrial Average
firstTradeDateEpochUtc: 694362600
timeZoneFullName: America/New_York
timeZoneShortName: EDT
uuid: fc24b2b0-ced7-33cc-9057-0b6d90973fc4
messageBoardId: finmb_INDEXDJI
gmtOffSetMilliseconds: -14400000
trailingPegRatio: None

**Comment by ValueRaider** [comment] 2023-05-18 10:56
Sounds like duplicate of #1519

**Closed** 2023-05-18 10:57 UTC
