### ISSUE TITLE
yfinance 0.2.3: Cannot load Ticker Info

### ISSUE THREAD

**Issue by Tatcher91** [ranaroussi/yfinance#1294] opened 2023-01-13 17:42 UTC
Dear Together,

I am facing the following situation:
yfinance module suddenly stopped providing Info today.
History request seems to be working however, while asking "actions" seems to provide "Empty Dataframe".
See the output below.

I found this issue from last month, resembling to my current situation, however its solution didn't solved my problem:
[https://github.com/ranaroussi/yfinance/issues/1246](url)

My questions would be:
Anybody facing this same problem currently?
Could you please help what may be the problem here and how to solve it?

**What I tried so far:**
-uninstall/reinstall yfinance package, with Pycharm restart (with reboot as well, just in case)
-update yfinance: pip install yfinance --upgrade --no-cache (it says "Requirement already satisfied" for all the packages)
-opening a new project with dummy requests
-debugging for the root cause, however I am quite a beginner in python, so no progress

**Environment information:**
I am using Windows, python 3.10, yfinance 0.2.3

**The example code I tried:**
asset = yf.Ticker("AAPL")
print(asset.history())
print(asset.actions)
print(asset.info["exchange"])

**Its output:**
                                 Open        High  ...  Dividends  Stock Splits
Date                                               ...                         
2022-12-13 00:00:00-05:00  149.500000  149.970001  ...        0.0           0.0
...
2023-01-13 00:00:00-05:00  132.029999  133.960007  ...        0.0           0.0

[22 rows x 7 columns]
Empty DataFrame
Columns: [Dividends, Stock Splits]
Index: []
Traceback (most recent call last):
  File "D:\...\main.py", line 613, in <module>
    print(asset.info["exchange"])
  File "D:\...\lib\site-packages\yfinance\ticker.py", line 138, in info
    return self.get_info()
  File "D...\lib\site-packages\yfinance\base.py", line 894, in get_info
    data = self._quote.info
  File "D:\...\lib\site-packages\yfinance\scrapers\quote.py", line 27, in info
    self._scrape(self.proxy)
  File "D:\...\lib\site-packages\yfinance\scrapers\quote.py", line 58, in _scrape
    quote_summary_store = json_data['QuoteSummaryStore']
TypeError: string indices must be integers

Thanks for the help in advance!

**Comment by ValueRaider** [comment] 2023-01-13 17:55
Duplicate of #1291

**Closed by ValueRaider** 2023-01-13 17:55 UTC

**Comment by Tatcher91** [comment] 2023-01-14 09:28
Sorry, wasn't aware that the other issue was already started. 
Thank you, the package is working now!
