### ISSUE TITLE
Failed downloads - "No timezone found, symbol may be delisted"

### ISSUE THREAD

**Issue by waterflyer** [ranaroussi/yfinance#1387] opened 2023-01-31 17:39 UTC
Hi yfinance team, 
`start_date = '2020-01-02'`
`end_date = '2022-01-01'`
`ticker_list = ['META', 'GOOG', 'ORCL', 'MSFT', 'AMZN']`
`data = yf.download(ticker_list, start=start_date, end=end_date, ignore_tz=True)[['Close']]`

I'm using the above code snippet to download 5 tickers' data, but I got the following error messages no matter if I changed `ignore_tz` to False or True.

[*********************100%***********************]  5 of 5 completed

5 Failed downloads:
- AMZN: No timezone found, symbol may be delisted
- META: No timezone found, symbol may be delisted
- GOOG: No timezone found, symbol may be delisted
- MSFT: No timezone found, symbol may be delisted
- ORCL: No timezone found, symbol may be delisted

![Screenshot 2023-01-31 at 10 29 45 AM](https://user-images.githubusercontent.com/23243356/215837936-eb4413ed-d24a-4a7b-b952-8f850670aad2.png)

yfinance version: 0.2.9
python version: 3.8.5
Operating system: Azure Machine Learning Studio or my kernel is Python 3.8 - AzureML

Please help me figure it out. I really appreciate any help you can provide.

**Comment by ValueRaider** [comment] 2023-01-31 17:48
Run this and report output:
```
for tkr in ticker_list:
	dat = yf.Ticker(tkr)
	tz = dat._fetch_ticker_tz(debug_mode=True, proxy=None, timeout=30)
	valid = yf.utils.is_valid_timezone(tz)
	print(f"{tkr}: tz='{tz}', valid={valid}")
```

**Comment by waterflyer** [comment] 2023-01-31 19:37
@ValueRaider Thank you for your response, as you suggested, after testing, this is the output
![image](https://user-images.githubusercontent.com/23243356/215864369-1a5619b6-55e6-4881-bf26-f058552e630e.png)

**Comment by Vidal4SigurRos** [comment] 2023-02-01 11:25
Are you behind a proxy?

**Comment by Vidal4SigurRos** [comment] 2023-02-01 11:37
@ValueRaider Not sure but I had the same and it was something related to tz retrieval from cache. 
I run your code above by specifying the proxy string instead of None and it worked.

**Comment by Vidal4SigurRos** [comment] 2023-02-01 15:25
Update from my side. I was trying to d/l new indices price history when I got the same issue. Here below the output with the check_validity code from @ValueRaider:

0.2.9
Download the historical stock prices for  ^GSPC:
1 Failed download:
- ^GSPC: No timezone found, symbol may be delisted

Download the historical stock prices for  ^DJI:
1 Failed download:
- ^DJI: No timezone found, symbol may be delisted

Download the historical stock prices for  ^IXIC:
1 Failed download:
- ^IXIC: No timezone found, symbol may be delisted

Download the historical stock prices for  ^NYA:
1 Failed download:
- ^NYA: No timezone found, symbol may be delisted

^GSPC: tz='America/New_York', valid=True
^DJI: tz='America/New_York', valid=True
^IXIC: tz='America/New_York', valid=True
^NYA: tz='America/New_York', valid=True
---
I've got 2 PC: one is behind proxy and one not. The one not behind a proxy works fine with this output:
yFinance ver.: 0.2.9
Download the historical stock prices for  ^DJI: 504 observation dowloaded.
Download the historical stock prices for  ^GSPC: 504 observation dowloaded.
Download the historical stock prices for  ^IXIC: 504 observation dowloaded.
DAX: tz='America/New_York', valid=True
SMI: tz='America/New_York', valid=True
^DJI: tz='America/New_York', valid=True
^GSPC: tz='America/New_York', valid=True
^IXIC: tz='America/New_York', valid=True
---
I debugged this issue and found that all is due to the fact that tz for the new tickers (e.g. ^GSPC) is not cached. 
As a consequence a new query is submitted (base.py _fetch_ticker_tz()) in order to retrieve it from yahoo and to cache it. 
For some reason the query fails and the tz it is not written into the cache (which is a SQLite3 db in C:\Users\<username>\AppData\Local\py-yfinance\tkr-tz.db under Win OS).
I'm still investigating the root cause behind the query failure but considering that on my PC not behind a proxy, it works I'm suspecting this is due to a non correct usage of the proxy in the _fetch_ticker_tz() query.
---
As a workaround I've just edited the kv table of cache db (e.g. with SQLiteStudio and manually added the row for ^GSPC and indeed it works.

HTH

**Comment by ValueRaider** [comment] 2023-02-01 15:43
> I'm suspecting this is due to a non correct usage of the proxy

Great clue. The timezone fetch was happening before `yfinance` had prepared the proxy. Can you try branch `fix/fetch-tz-via-proxy`

**Comment by Vidal4SigurRos** [comment] 2023-02-01 15:52
Final update from my side.

I can confirm the issue is due to the format of proxy which goes as input to the web query base.py _fetch_ticker_tz().

Such kind of queries require a string for the proxy but in input the proxy information is a dict.

Therefore a code like this one (which has been already used elesewhere) in line 1209 in base.py _fetch_ticker_tz() after the try statement ensures it is a string and fix the issue:
if proxy is not None:
    if isinstance(proxy, dict) and "https" in proxy:
       proxy = proxy["https"]

hope it will be integrated into hotfix/proxy soon.

Be aware that in your main codes proxies has to be declared as dictionary.
E.g.: my_proxy={'http':'<ip-address>:<port>', 'https':'<ip-address>:<port>'}
yf.dowload(ticker, start=my_start, end=my_end, proxy=my_proxy)

**Comment by Vidal4SigurRos** [comment] 2023-02-01 15:53
> 
I read now your message :-). Let me try your fix...

**Comment by Vidal4SigurRos** [comment] 2023-02-01 16:55
You get the same as error as before.

**Comment by Vidal4SigurRos** [comment] 2023-02-01 17:15
I see what you mean... Indeed all the data request are demanded to TickerData object which ensures correct proxy format with get() and _get_proxy() methods

**Comment by ValueRaider** [comment] 2023-02-01 17:30
Can you switch to branch `hotfix/proxy` and run the new test: `tests/ticker.py :: test_goodTicker_withProxy`. Obviously set a proxy in `setUpClass`.

**Comment by Vidal4SigurRos** [comment] 2023-02-01 17:51
In the meantime I did the following test by using old-style debug approach and insert print statements in base.py and data.py
(To be noted that to test we need a brand new ticker never cached before). For a cached ticker both codes (i.e. with or without the last line) work.
Differences seem related to frozendict usage behind the scene.... and removing the last line seems indeed to be just a side-effect workaround

**With the last line:**

        # setup proxy in requests format
        if proxy is not None:
            if isinstance(proxy, dict) and "https" in proxy:
                proxy = proxy["https"]
            proxy = {"https": proxy}

**Output:**
Download the historical stock prices for  ^N225:

base.py, TickerBase.history():after fix/fetch_tx_via_proxy block:proxy: {'https': '10.xx.xxx.xx:pppp'}
base.py, TickerBase:_fetch_ticker_tz:before _data.cache_get-->proxy: {'https': '10.xx.xxx.xx:pppp'}
data.py,TickerData::get:before proxy reformat:proxy--> frozendict.frozendict({'https': '10.xx.xxx.xx:pppp'})
data.py,TickerData::get:after proxy reformat and before _session.get():proxy--> {'https': frozendict.frozendict({'https': '10.xx.xxx.xx:pppp'})}

1 Failed download:
^N225: No timezone found, symbol may be delisted


**Without the last line:**

        # setup proxy in requests format
        if proxy is not None:
            if isinstance(proxy, dict) and "https" in proxy:
                proxy = proxy["https"]

**Output**
Download the historical stock prices for  ^N225:

base.py, TickerBase.history():after fix/fetch_tx_via_proxy block:proxy: 10.xx.xxx.xx:pppp
base.py, TickerBase:_fetch_ticker_tz:before _data.cache_get-->proxy: 10.xx.xxx.xx:pppp
data.py,TickerData::get:before proxy reformat:proxy--> 10.xx.xxx.xx:pppp
data.py,TickerData::get:after proxy reformat and before _session.get():proxy--> {'https': '10.xx.xxx.xx:pppp'}
data.py,TickerData::get:before proxy reformat:proxy--> 10.xx.xxx.xx:pppp
data.py,TickerData::get:after proxy reformat and before _session.get():proxy--> {'https': '10.xx.xxx.xx:pppp'}

490 observation dowloaded.

**Comment by ValueRaider** [comment] 2023-02-01 18:05
Can you format the output better?

What is `proxy` *inside* `TickerData::get()`?

**Comment by Vidal4SigurRos** [comment] 2023-02-01 18:11
![image](https://user-images.githubusercontent.com/124048111/216127312-e00da80c-d9b3-4373-9d14-4334768b70bb.png)

**Comment by ValueRaider** [comment] 2023-02-01 18:12
Run this: `dat._fetch_ticker_tz(debug_mode=True, proxy=proxy, timeout=10)` It should print any that's occurring because of `frozendict`

**Comment by ValueRaider** [comment] 2023-02-01 18:17
Sorry, I've edited now

**Comment by Vidal4SigurRos** [comment] 2023-02-01 18:31
Hope I've understood well (sorry if I left my print):
- insert: yf.Ticker(ticker)._fetch_ticker_tz(debug_mode=True, proxy=proxy, timeout=10)
- revert to "with last line" version
- run it against two indexes: FTSE and NIKKEI
 
**HTH**
**Output**
0.2.9

base.py, TickerBase:_fetch_ticker_tz:before _data.cache_get-->proxy: {'http': '10.xx.xxx.xx:pppp', 'https': '10.xx.xxx.xx:pppp'}
data.py,TickerData::get:before proxy reformat:proxy--> frozendict.frozendict({'http': '10.xx.xxx.xx:pppp', 'https': '10.xx.xxx.xx:pppp'})
data.py,TickerData::get:after proxy reformat and before _session.get():proxy--> {'https': frozendict.frozendict({'http': '10.xx.xxx.xx:pppp', 'https': '10.xx.xxx.xx:pppp'})}

Failed to get ticker '^N225' reason: expected string or bytes-like object

Download the historical stock prices for  ^N225:
base.py, TickerBase.history():after fix/fetch_tx_via_proxy block:proxy: {'https': '10.xx.xxx.xx:pppp'}
data.py,TickerData::get:before proxy reformat:proxy--> frozendict.frozendict({'https': '10.xx.xxx.xx:pppp'})
data.py,TickerData::get:after proxy reformat and before _session.get():proxy--> {'https': frozendict.frozendict({'https': '10.xx.xxx.xx:pppp'})}

 
1 Failed download:
- ^N225: No data found for this date range, symbol may be delisted


base.py, TickerBase:_fetch_ticker_tz:before _data.cache_get-->proxy: {'http': '10.xx.xxx.xx:pppp', 'https': '10.xx.xxx.xx:pppp'}
data.py,TickerData::get:before proxy reformat:proxy--> frozendict.frozendict({'http': '10.xx.xxx.xx:pppp', 'https': '10.xx.xxx.xx:pppp'})
data.py,TickerData::get:after proxy reformat and before _session.get():proxy--> {'https': frozendict.frozendict({'http': '10.xx.xxx.xx:pppp', 'https': '10.xx.xxx.xx:pppp'})}

Failed to get ticker '^FTSE' reason: expected string or bytes-like object

Download the historical stock prices for  ^FTSE:
base.py, TickerBase.history():after fix/fetch_tx_via_proxy block:proxy: {'https': '10.xx.xxx.xx:pppp'}
base.py, TickerBase:_fetch_ticker_tz:before _data.cache_get-->proxy: {'https': '10.xx.xxx.xx:pppp'}
data.py,TickerData::get:before proxy reformat:proxy--> frozendict.frozendict({'https': '10.xx.xxx.xx:pppp'})
data.py,TickerData::get:after proxy reformat and before _session.get():proxy--> {'https': frozendict.frozendict({'https': '10.xx.xxx.xx:pppp'})}

1 Failed download:
- ^FTSE: No timezone found, symbol may be delisted

**Comment by Vidal4SigurRos** [comment] 2023-02-01 18:34
fyi I also run it without the last line and it works, but I get the same message
"Failed to get ticker '^FTSE' reason: expected string or bytes-like object"

HTH

**Comment by Vidal4SigurRos** [comment] 2023-02-01 18:37
IMHO from a cleaner design I think you are right and we should leave the last line. The root cause seems to be in another point and related to frozendict. Removing the last line and pass proxy as a string appears to be a workaround...

**Comment by ValueRaider** [comment] 2023-02-01 19:05
I've pushed a potential fix, try again.

**Comment by Vidal4SigurRos** [comment] 2023-02-01 19:16
replaced data.py with your last version

**Output**
0.2.9
base.py, TickerBase:_fetch_ticker_tz:before _data.cache_get-->proxy: {'http': '10.xx.xxx.xx:pppp', 'https': '10.xx.xxx.xx:pppp'}
Failed to get ticker '^N225' reason: type object 'frozendict.frozendict' has no attribute 'frozendict'
Download the historical stock prices for  ^N225:
base.py, TickerBase.history():after fix/fetch_tx_via_proxy block:proxy: {'https': '10.xx.xxx.xx:pppp'}
base.py, TickerBase:_fetch_ticker_tz:before _data.cache_get-->proxy: {'https': '10.xx.xxx.xx:pppp'}

1 Failed download:
^N225: No timezone found, symbol may be delisted

**Comment by ValueRaider** [comment] 2023-02-01 19:18
> type object 'frozendict.frozendict' has no attribute 'frozendict'

Fixed.

**Comment by Vidal4SigurRos** [comment] 2023-02-01 19:40
but still not working

**Output**
0.2.9
base.py, TickerBase:_fetch_ticker_tz:before _data.cache_get-->proxy: {'http': '10.xx.xxx.xx:pppp', 'https': '10.xx.xxx.xx:pppp'}
Failed to get ticker '^N225' reason: expected string or bytes-like object
Download the historical stock prices for  ^N225:
base.py, TickerBase.history():after fix/fetch_tx_via_proxy block:proxy: {'https': '10.xx.xxx.xx:pppp'}
base.py, TickerBase:_fetch_ticker_tz:before _data.cache_get-->proxy: {'https': '10.xx.xxx.xx:pppp'}


1 Failed download:
^N225: No timezone found, symbol may be delisted

**Comment by Vidal4SigurRos** [comment] 2023-02-01 19:50
Just to remark that I'm testing with the last base.py in the `hotfix/proxy` branch modified with uncommented line 514:
`proxy = {"https": proxy}`

**Comment by ValueRaider** [comment] 2023-02-01 19:51
I can't keep debugging like this, via you. Can you take over? Focus on the `get` function, maybe the other arguments need to be converted `frozendict` -> `dict`

**Comment by Vidal4SigurRos** [comment] 2023-02-01 19:55
ok.

**Comment by Vidal4SigurRos** [comment] 2023-02-01 20:20
may I have write access to the code as contributor?

**Comment by ValueRaider** [comment] 2023-02-01 20:36
I can't modify repo permissions.

**Comment by ValueRaider** [comment] 2023-02-01 21:22
Thanks. I've implemented and pushed. I also improved error messaging so next time it won't take this long to debug, so if still failing just do `Ticker.history(..., raise_errors=True)`

For certainty can you run the test? Put your proxy in `tests/ticker.py::setUpClass` then run:
```
python -m unittest tests.ticker.TestTicker.test_goodTicker_withProxy
```

**Comment by ValueRaider** [comment] 2023-02-01 22:36
@waterflyer We hijacked your Issue to debug proxy. Were you using a proxy?

**Comment by waterflyer** [comment] 2023-02-02 00:22
Yeah, I think so because we have to connect to our company’s VPN while using AML studio. Thank you for your debugging and hot fixing, so can I update the package and use it now? On Feb 1, 2023, at 3:36 PM, ValueRaider ***@***.***> wrote:﻿
@waterflyer We hijacked your Issue to debug proxy. Were you using a proxy?

**Comment by ValueRaider** [comment] 2023-02-02 00:40
Not released yet, needs a comprehensive test to be run in case proxy broken elsewhere. Maybe you can run test, I can't because no proxy. Grab branch `hotfix/proxy` (instructions #1080) then [do this](https://github.com/ranaroussi/yfinance/issues/1387#issuecomment-1412743359)

**Comment by waterflyer** [comment] 2023-02-02 00:42
Ok, sounds good, I will try it out tomorrow morning when I start my work.

**Comment by ValueRaider** [comment] 2023-02-02 00:43
Sorry, deleted reply, needed to change after more thought.

You only think so? You should certainly know if using a proxy, because you must set `download(proxy=...)`

**Comment by waterflyer** [comment] 2023-02-02 00:54
Ok, all good. I will double-check tomorrow and will keep that in mind, I
must set download(proxy=... ). Thanks!

**Comment by ValueRaider** [comment] 2023-02-02 00:55
No you don't understand. If you were not setting proxy, then you were not using a proxy.

**Comment by Vidal4SigurRos** [comment] 2023-02-03 18:41
> Thanks. I've implemented and pushed. I also improved error messaging so next time it won't take this long to debug, so if still failing just do `Ticker.history(..., raise_errors=True)`
> 
> For certainty can you run the test? Put your proxy in `tests/ticker.py::setUpClass` then run:
> ```
> python -m unittest tests.ticker.TestTicker.test_goodTicker_withProxy
> ```

--

    `@classmethod

    def setUpClass(cls):

        cls.session = requests_cache.CachedSession(backend='memory')

        proxies = {'http': '10.xx.xxx.xx:pppp', 'https': '10.xx.xxx.xx:pppp'}

        cls.proxy = proxies
`
---

`======================================================================

FAIL: test_goodTicker_withProxy (tests.ticker.TestTicker)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda\Lib\site-packages\yfinance\tests\ticker.py", line 157, in test_goodTicker_withProxy

    self.assertIsNotNone(v)

AssertionError: unexpectedly None
`

**Comment by ValueRaider** [comment] 2023-02-03 19:32
Can you debug that?

**Comment by vidalmarco** [comment] 2023-02-04 20:04
@ValueRaider  Good news! :) 
When called from my program the hotfix works even on fundamentals of IBM (used in your test, hence there is no "reached access limit issue" from my side) and on any valid listed symbol . 
I was not able to do it from your test. Can you resummarize where I fail?

in my main() 👍 
```
   # set-up proxy
        proxies = {'http': '10.xx.xxx.xx:pppp', 'https': '10.xx.xxx.xx:pppp'}
        session = requests_cache.CachedSession(backend='memory')
        session.proxies = proxies
        for ticker in ticker_list:
            symbol = yf.Ticker(ticker, session=session)
            # print all static fundamentals attributes of Ticker
            print_fundamentals(symbol)
```

in your test setUpClass 👎 
```
    @classmethod
    def setUpClass(cls):
        cls.session = requests_cache.CachedSession(backend='memory')
        proxies = {'http': '10.xx.xxx.xx:pppp', 'https': '10.xx.xxx.xx:pppp'}
        cls.proxy = proxies
```

**Comment by ValueRaider** [comment] 2023-02-04 20:11
You didn't fail, and I never said or implied you did. Python executed to line 157 of `ticker.py`, meaning all asserts before passed successfully. Something wrong in line 157.

**Comment by vidalmarco** [comment] 2023-02-04 21:14
Yes.
```
def print_fundamentals(symbol):
    print("Shares:", symbol.shares)
    print("Info:", [symbol.info](http://symbol.info/))
    print("Actions:", symbol.actions)
    print("Dividends:", symbol.dividends)
    print("major_holders:", symbol.major_holders)
    print("institutional_holders:", symbol.institutional_holders)
    print("mutualfund_holders:", symbol.mutualfund_holders)
    print("capital_gains:", symbol.capital_gains)
    print("calendar:", symbol.calendar)
    print("earnings:", symbol.earnings)
    print("quarterly_earnings:", symbol.quarterly_earnings)
    print("income_stmt:", symbol.income_stmt)
    print("quarterly_income_stmt:", symbol.quarterly_income_stmt)
    print("balance_sheet:", symbol.balance_sheet)
    print("quarterly_balance_sheet:", symbol.quarterly_balance_sheet)
    print("cash_flow:", symbol.cash_flow)
    print("quarterly_cash_flow:", symbol.quarterly_cash_flow)
    print("recommendations_summary:", symbol.recommendations_summary)
    print("analyst_price_target:", symbol.analyst_price_target)
    print("revenue_forecasts:", symbol.revenue_forecasts)
    print("sustainability:", symbol.sustainability)
    print("recommendations:", symbol.recommendations)
    print(news:, symbol.news)
    print("earnings_trend:", symbol.earnings_trend)
    print("earnings_dates:", symbol.earnings_dates)
    print("earnings_forecasts:", symbol.earnings_forecasts)
    print("options:", symbol.options)
    print("history_metadata:", symbol.history_metadata)
    # yet to be implemented
    # print("market_cap:", symbol.market_cap)
    # print("ISIN:", symbol.isin)
```
**Output**
```
Shares:       BasicShares
Year            
2019    887200000
2020    890300000
2021    896000000
```
[...]
```
major_holders:         0                                      1
0   0.09%        % of Shares Held by All Insider
1  58.44%       % of Shares Held by Institutions
2  58.49%        % of Float Held by Institutions
3    2922  Number of Institutions Holding Shares
```

[...]

**when symbol.get_major_holders() is called directly:**
```
symbol.get_major_holders():         0                                      1
0   0.09%        % of Shares Held by All Insider
1  58.44%       % of Shares Held by Institutions
2  58.49%        % of Float Held by Institutions
3    2922  Number of Institutions Holding Shares
```

**Comment by ValueRaider** [comment] 2023-02-04 21:16
Of course it worked, you didn't set proxy argument. Try again setting `proxy`

**Comment by vidalmarco** [comment] 2023-02-04 21:37
with `symbol.get_major_holders(proxy=proxies)` I got the same

**Comment by ValueRaider** [comment] 2023-02-04 21:51
So there's no good reason for the test to fail. Please investigate why it's failing and identify fix, so `test_goodTicker_withProxy` runs to completion.

**Comment by ValueRaider** [comment] 2023-02-04 21:53
Ok. Are you capable of debugging the test failing?

**Comment by vidalmarco** [comment] 2023-02-04 22:06
Yes, wait...

**Comment by vidalmarco** [comment] 2023-02-04 23:57
`holders.py` in `try `block before `_data.cache_get` proxy is valued while in `cache_get `before `return` is `None`. 
:-o Can't understand why... could cache maxsize influence?

**Comment by ValueRaider** [comment] 2023-02-05 00:07
It's actually very simple, basic Python. `holders.py` is passing `proxy` as 2nd argument, but `cache_get()` expects proxy as 4th.

I've patched, try again.

**Comment by vidalmarco** [comment] 2023-02-05 00:18
my god...:D

**Comment by vidalmarco** [comment] 2023-02-05 00:56
after having fixed on myself the ` get_shares_full() ` I moved `get_isin()` at the end and I could verify that it is the only one broken remain. By commenting it I could get an OK

**Comment by vidalmarco** [comment] 2023-02-05 12:11
I spent some time on debugging the `get_isin` method.
After some failures (always getting HTTPS Tunnel 407 failure) I've tried to test it via curl. 

**First** (as generated by `get_isin`)
`curl -x 10.xx.xxx.xx:pppp https://markets.businessinsider.com/ajax/SearchController_Suggest?query=IBM`
**curl: (56) Received HTTP code 407 from proxy after CONNECT**

**Second** (specify a user)
`curl -x 10.xx.xxx.xx:pppp https://markets.businessinsider.com/ajax/SearchController_Suggest?query=NOVARTIS -U <my_username>`
**Enter proxy password for user '<my_username>':
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.**

**Third** (specify a user and a ssl cert verification check = False)
`curl -x 10.xx.xxx.xx:pppp https://markets.businessinsider.com/ajax/SearchController_Suggest?query=IBM -U <my_username> --ssl-no-revoke`

**Enter proxy password for user '<my_username>':
mmSuggestDeliver(0, new Array("Name", "Category", "Keywords", "Bias", "Extension", "IDs"), new Array(new Array("IBM Corp. (International Business Machines)", "Stocks", "IBM|US4592001014|IBM||IBM", "75", "", "ibm|IBM|1|389"),new Array("The Options Clearing Corp OCC OPRA - Package Basket for ETD Developed from IBM", "Stocks", "IBM1|XD0114686534|IBM1||", "75", "", "ibm1|IBM1|1|369657383"),new Array("IBJ Inc", "Stocks", "|JP3104960004|||", "75", "", "ibj||1|1349241"),new Array("IBIDEN CO LTDShs", "Stocks", "IBIDF|JP3148800000|IBIDF||", "75", "", "ibidf|IBIDF|1|12090"),new Array("Masmovil Ibercom SA Bearer Shs", "Stocks", "MMBMF|ES0184696104|MMBMF||", "75", "", "mmbmf|MMBMF|1|21595152"),new Array("IMMOFINANZ", "Stocks", "|AT0000A21KS2|||", "75", "", "immofinanz||1|19145188"),new Array("ImmuCell", "Stocks", "ICCC|US4525253062|ICCC||", "75", "", "iccc|ICCC|1|2819"),new Array("Al Hassan Ghazi Ibrahim Shaker Co. Bearer Shs", "Stocks", "|SA12I0OGIV12|||", "75", "", "al_hassan_ghazi_ibrahim_shaker||1|27215953"),new Array("Immuron Ltd", "Stocks", "|AU000000IMC7|||", "75", "", "immuron||1|25442"),new Array("ImmunoGen Inc.", "Stocks", "IMGN|US45253H1014|IMGN||IMGN", "75", "", "imgn|IMGN|1|613")), 10, 0);** 👍 

**Fourth** (w/o a user and a ssl cert verification check = False)
`curl -x 10.xx.xxx.xx:pppp https://markets.businessinsider.com/ajax/SearchController_Suggest?query=IBM --ssl-no-revoke`
**curl: (56) Received HTTP code 407 from proxy after CONNECT**

Any ideas on how to overcome the usage of username? Also I don't think it's advisable to use the verify=False (equivalent of --ssl-no-revoke option) in `session.get call`

**Comment by ValueRaider** [comment] 2023-02-05 12:52
@vidalmarco That feels like a distinct issue, can you move to a new Issue if you agree.

**Comment by vidalmarco** [comment] 2023-02-05 15:29
> @vidalmarco That feels like a distinct issue, can you move to a new Issue if you agree.

Moved to #1399

**Comment by Yats11** [comment] 2023-02-19 21:58
I am not using a VPN but have the same problem when downloading multiple ticks. However, it works when downloading one tick at a time.

# -  8804.T: No timezone found, symbol may be delisted
# -  9001.T: No timezone found, symbol may be delisted
all_ticks = yf.download(tickers, start, end, interval='1d', progress=False)["Adj Close"]


# Works fine!
for ticker in tickers:
    current_ticker_price = yf.download(ticker, start, end, interval='1d', progress=False)["Adj Close"]

**Comment by ValueRaider** [comment] 2023-02-19 22:17
@Yats11 Run this code, what happens:
```
for t in tickers:
  print(t , yf.utils.get_tz_cache().lookup(t))
```

**Comment by ValueRaider** [comment] 2023-02-19 22:35
Problem with this issue is I can't reproduce, so you have to help debug. Switch to Git branch `debug/download-timezone`, it will print out useful debug messages. Instructions #1080. Report back what happens.

**Comment by YUYANGSHEN** [comment] 2023-03-11 14:28
I have the same error “No timezone found, symbol may be delisted”. how to solve it?

**Comment by ValueRaider** [comment] 2023-03-11 14:57
This might be duplicate of #1268

**Closed** 2023-04-11 10:33 UTC

**Comment by stefan-sherwood** [comment] 2024-02-21 03:09
For what it's worth, I had the same problem with the same symptom (yFinance == 0.2.36) and the root cause was that the timezone lookup was failing as a result of `fc.yahoo.com` being in the AdGuard blocklist _1Hosts (Lite)_.

I am not using an explicit proxy with yFinance.

I could fix the problem by either manually enabling the domain in AdGuard or changing the yFinance code to use `finance.yahoo.com` instead of `fc.yahoo.com`

_data.py, line 160_
```
        # To avoid infinite recursion, do NOT use self.get()
        # - 'allow_redirects' copied from @psychoz971 solution - does it help USA?
        response = self._session.get(
            url='https://finance.yahoo.com',
            headers=self.user_agent_headers,
            proxies=proxy,
            timeout=timeout,
            allow_redirects=True)

```

**Comment by SamuelBarbosa97** [comment] 2024-09-10 04:59
I've tried VPN and change the 'finance.yahoo.com' but nothing worked, does anyone have any more tips?

**Comment by ValueRaider** [comment] 2024-09-17 19:53
@SamuelBarbosa97 Open a new bug report

**Comment by satyaseelan** [comment] 2025-01-14 10:46
My error went away after 
pip uninstall yfinance
pip install yfinance --upgrade --no-cache-dir

**Comment by Nikta96** [comment] 2025-01-30 18:03
hi 
I have error in Jupiter after running this code
gme_data = gme.history(period = "max")
the errore is 
$GME: possibly delisted; no timezone found
what should i do?? please help me

**Comment by LeMquicode** [comment] 2025-03-08 21:41
Hi, a big thank you to @harishydav , using a VPN it worked fine.  For one ticker and for multiple tickers. But, it is annoying to think 'Oh I need to use yfinance module I have to connect my VPN'.  So I followed what @satyaseelan said and it worked perfectly. so just do the following 
pip uninstall yfinance
pip install yfinance --upgrade --no-cache-di

Regards ;)

**Comment by Kevin20250000000** [comment] 2025-05-09 15:35
> pip uninstall yfinance pip install yfinance --upgrade --no-cache-dir之后我的错误消失了

Problem is solved! Thank you!
