### ISSUE TITLE
How to get marketcap of many tickers? when i get that ,error is as follows

### ISSUE THREAD

**Issue by xueyongtu** [ranaroussi/yfinance#839] opened 2021-09-20 14:13 UTC
HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/A/financials (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000134E53E6700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by atk5025** [comment] 2021-09-21 02:38
this looks like you've tried to access the API too many times recently. Stop hitting the API for a little bit then try again.

**Comment by ValueRaider** [comment] 2023-01-06 21:14
Duplicate of #742

**Closed by ValueRaider** 2023-01-06 21:14 UTC
