### ISSUE TITLE
Error When Decrypting Data 

### ISSUE THREAD

**Issue by STEVEN-STARK** [ranaroussi/yfinance#1339] opened 2023-01-25 17:38 UTC
I wrote a program that uses the yfinance library to retrieve the current indices for the Dow, NASDAQ and S&P every 15 minutes while the exchanges are open.  The program executes on a Windows 7 platform using Python version 3.8.1 . The installed version of yfinance is 0.2.4 .

The program functioned flawlessly until last night (24 January).  However, with no changes made to the code, not only did the program generate an exception, but it caused the Python interpreter to crash!!   

The code that generated the exception is shown below:

#-------------------------------------------------------------------
# Retrieve the DOW index from the Yahoo server:
hDow=yf.Ticker ('^DJI')
strTag="regularMarketPrice"
nDJ_Index=int (hDow.info [strTag])        
strDJ_Index=(("%d") % nDJ_Index)
print ("strDJ_Index=",strDJ_Index)

The traceback error message is shown below:

Traceback (most recent call last):
  File "E:\Projects\WebServer\Version 1.5.5\StockDataProgram.py", line 343, in <module>
    pStck.GetSendStockInfo ("False")
  File "E:\Projects\WebServer\Version 1.5.5\StockDataProgram.py", line 198, in GetSendStockInfo
    nDJ_Index=int (hDow.info (strTage)) 
  File "E:\Program File (x86)\Python Version 3.8.1\lib\site-packages\yfinance\ticker.py", line 138, in info
    return self.get_info()
  File "E:\Program File (x86)\Python Version 3.8.1\lib\site-packages\yfinance\base.py", line 895, in get_info
    data = self._quote.info
  File "E:\Program File (x86)\Python Version 3.8.1\lib\site-packages\yfinance\scrapers\quote.py", line 27, in info
    self._scrape(self.proxy)
  File "E:\Program File (x86)\Python Version 3.8.1\lib\site-packages\yfinance\scrapers\quote.py", line 56, in _scrape
    json_data = self._data.get_json_data_stores(proxy=proxy)
  File "E:\Program File (x86)\Python Version 3.8.1\lib\site-packages\yfinance\data.py", line 40, in wrapped
    return func(*args, **kwargs)
  File "E:\Program File (x86)\Python Version 3.8.1\lib\site-packages\yfinance\data.py", line 202, in get_json_data_stores
    stores = decrypt_cryptojs_aes_stores(data) 
  File "E:\Program File (x86)\Python Version 3.8.1\lib\site-packages\yfinance\data.py", line 73, in decrypt_cryptojs_aes_stores
    raise Exception(msg)    
    
I am at a complete loss to understand how this could happen!!  The only thing that I can think of is that Yahoo has changed their encryption mechanism which is causing the code to fail.  The reason I say this is that I had yfinance version 0.2.3 running on a Raspberry Pi and, just like this case, one day it simply stopped working!  The on-line forums indicated that it was related to a change in the encryption mechanism.

**Comment by lispoz** [comment] 2023-01-26 01:38
I have the same problem. Also no changes to my code since it worked.

Traceback

$>python3 yf/py-gethist-range.py 'NAB.AX' 'NAB.AX' '2023-01-04' '2023-01-28' 'temp.data.lisp' 'temp.smy.lisp'
(echo) 
[py-gethist-range.py.txt](https://github.com/ranaroussi/yfinance/files/10505405/py-gethist-range.py.txt)
yf/py-gethist-range.py NAB.AX NAB.AX 2023-01-04 2023-01-28 temp.data.lisp temp.smy.lisp
**YF Version last 0.2.4 0.2.4**
Traceback (most recent call last):
  File "/hd/hd-home/finance/src/daily/yf/py-gethist-range.py", line 17, in <module>
    if ('exchange' in aaaa.info) :
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/base.py", line 895, in get_info
    data = self._quote.info
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 27, in info
    self._scrape(self.proxy)
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 56, in _scrape
    json_data = self._data.get_json_data_stores(proxy=proxy)
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/data.py", line 40, in wrapped
    return func(*args, **kwargs)
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/data.py", line 202, in get_json_data_stores
    stores = decrypt_cryptojs_aes_stores(data)
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/data.py", line 73, in decrypt_cryptojs_aes_stores
    raise Exception(msg)
**Exception: Yahoo has again changed data format, yfinance now unsure which key(s) is for decryption:** '0e56e61daac9'-><class 'str'> , '0e56e61daac9'-><class 'str'> , '0e56e61daac9'-><class 'str'> , '0e56e61daac9'-><class 'str'> , (MUCH more of the same for many pages). 

Source of script attached (with .txt suffix added to make github uploader happy)

**Comment by lispoz** [comment] 2023-01-26 01:54
After upgrading to 0.2.6 I get a slightly different message. Same script as above.

$>python3 yf/py-gethist-range.py 'NAB.AX' 'NAB.AX' '2023-01-04' '2023-01-28' 'temp.data.lisp' 'temp.smy.lisp'
yf/py-gethist-range.py NAB.AX NAB.AX 2023-01-04 2023-01-28 temp.data.lisp temp.smy.lisp
YF Version last 0.2.4 0.2.6
Traceback (most recent call last):
  File "/hd/hd-home/finance/src/daily/yf/py-gethist-range.py", line 17, in <module>
    if ('exchange' in aaaa.info) :
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/ticker.py", line 142, in info
    return self.get_info()
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/base.py", line 1220, in get_info
    data = self._quote.info
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 96, in info
    self._scrape(self.proxy)
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 125, in _scrape
    json_data = self._data.get_json_data_stores(proxy=proxy)
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/data.py", line 40, in wrapped
    return func(*args, **kwargs)
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/data.py", line 256, in get_json_data_stores
    stores = decrypt_cryptojs_aes_stores(data)
  File "/home/tim-ml/.local/lib/python3.10/site-packages/yfinance/data.py", line 190, in decrypt_cryptojs_aes_stores
    raise Exception("yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers")
**Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers**

**Comment by ValueRaider** [comment] 2023-01-26 02:04
Duplicate of #1329

**Closed** 2023-01-26 02:04 UTC
