### ISSUE TITLE
Incorrect data for some symbols

### ISSUE THREAD

**Issue by diogobotelho** [ranaroussi/yfinance#829] opened 2021-09-02 01:58 UTC
Please take a look at this below. For "SVA" yfinance only extacts data up to 2019-02-25. If I use the start parameter, I get data for 2020. 

```
yf.download("SVA")
[*********************100%***********************]  1 of 1 completed
Out[7]: 
            Open    High     Low  Close  Adj Close  Volume
Date                                                      
2012-06-18  2.00  2.0700  2.0000   2.01       2.01   47109
2012-06-19  2.05  2.0700  2.0200   2.02       2.02   13740
2012-06-20  2.03  2.0700  2.0300   2.05       2.05   31682
2012-06-21  2.03  2.1000  2.0000   2.07       2.07   46439
2012-06-22  2.05  2.1000  2.0300   2.05       2.05    6909
         ...     ...     ...    ...        ...     ...
2019-02-19  6.45  6.5099  6.4500   6.47       6.47    5618
2019-02-20  6.48  6.5100  6.4300   6.43       6.43    8415
2019-02-21  6.50  6.5100  6.4700   6.49       6.49    7744
2019-02-22  6.49  6.5800  6.2501   6.47       6.47    8227
2019-02-25  6.47  6.4700  6.4700   6.47       6.47       0

[1682 rows x 6 columns]

yf.download("SVA", start="2020-01-01" )
[*********************100%***********************]  1 of 1 completed
Out[8]: 
            Open  High   Low  Close  Adj Close  Volume
Date                                                  
2020-01-02  6.47  6.47  6.47   6.47       6.47       0
```

**Comment by homeboykeroro** [comment] 2021-09-06 11:46
I have similar problems. I found out some symbols' volume are not accurate. For example, "INZY" actual volume of on August 20 is 26300 but the value in dataframe shows 263000.

**Comment by jemoakESS** [comment] 2021-09-15 22:18
I have seen similar problems for a while now, too. I query a history of ~2 years on various stocks. The last few entries for the daily volume of many of the queries (but not all) appear to be off by a factor of 100X, i.e. the system is multiplying the actual volume by 100 for about the last month's worth of entries (but not always a month's worth, so can't 'predict' the behavior in order to correct it).

I also have difficulty getting a complete query, often leaving off the last few days of the requested period - and not having the last few days can be problematic. A simple 'try again' appears to work.

Here is an example (my script simply creates .csv files from the panda frame) which shows both problems (symbol "A"). The query end date should be 9/15 but the data ends on 9/3. And the volumes are increased by 100X at the end of the file.
![image](https://user-images.githubusercontent.com/58604595/133516967-2db702e1-ebb5-4658-baa3-f235b09bb718.png)

**Comment by silvavn** [comment] 2021-10-13 16:45
This is a duplicate of #262

**Closed by silvavn** 2021-10-13 16:45 UTC
Labels: duplicate
