### ISSUE TITLE
dividendDate missing

### ISSUE THREAD

**Issue by leodamasceno** [ranaroussi/yfinance#996] opened 2022-05-05 20:04 UTC
Hey there. First of all, thanks for all the work you guys put into this project.

I've been using for a while and It's been working great for my project. Unfortunately, I am trying to add the dividendDate, also known as "Payout date", I can see it is available in the **Statistics** tab in Yahoo Finance, but I don't see it in the output of **info**.

Here's my code:
```
import yfinance as yahooFinance

StockInfo = yahooFinance.Ticker("O")

print(StockInfo.info)
```

I can see the **exDividendDate** is there but I can't find the payout date, it would be awesome if you could add it.

Thanks

**Comment by ValueRaider** [comment] 2023-07-09 21:29
Duplicate of #568

**Closed by ValueRaider** 2023-07-09 21:29 UTC
Labels: enhancement
