### ISSUE TITLE
 getting 0 volume data when dowloading last 30 days 15m data of a Forex ticker USDJPY, other data are ok. 

### ISSUE THREAD

**Issue by Tony75I** [ranaroussi/yfinance#1376] opened 2023-01-29 13:35 UTC
getting 0 volume data when dowloading last 30 days 15m data of a Forex ticker USDJPY, other data are ok.

**Comment by Tony75I** [comment] 2023-01-29 13:50
possibly volume data aren't available for Forex?

**Comment by ValueRaider** [comment] 2023-01-29 13:54
Duplicate of #1375.

**Closed by ValueRaider** 2023-01-29 13:54 UTC
