### ISSUE TITLE
yfinance 0.1.*: Unable to load ticker information

### ISSUE THREAD

**Issue by untucked** [ranaroussi/yfinance#1246] opened 2022-12-17 01:07 UTC
- Info about your system:
yfinance version: '0.1.90'
  - operating system: 
  -windows
- Simple code that reproduces your problem
```
ticker = 'AAPL'
print('ticker: %s'%(ticker))
yf_info = yf.Ticker(ticker)
bs = yf_info.balance_sheet
print(bs)
```
- The error message
Returns empty array: when I print bs
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

**Comment by BrsrkrBrown** [comment] 2022-12-17 01:34
Having similar issue, when trying to print regularMarketPrice and volume.
printing yf.Ticker(ticker).info returns:
{'regularMarketPrice': None, 'preMarketPrice': None, 'logo_url': '', trailingPegRatio':None}

**Comment by Travis-Barton** [comment] 2022-12-17 02:09
Same problem for me on all stocks it seems.
I get `{'regularMarketPrice': None, 'preMarketPrice': None, 'logo_url': ''}` for any `info`

**Comment by mrtomcollins** [comment] 2022-12-17 07:53
Same problem for me

**Comment by valankar** [comment] 2022-12-17 08:40
Same here. Problem seems to have started today, perhaps some issue with Yahoo or API.

**Comment by galashour** [comment] 2022-12-17 09:26
same here

**Comment by ValueRaider** [comment] 2022-12-17 11:16
Looks like Yahoo has compressed or encrypted the data stores embedded in html that `yfinance` relied upon. E.g.

Before (via my session cache):
```
root.App || (root.App = {});
root.App.now = 1671025861087;
root.App.main = {"context":{"dispatcher":{"stores":{"PageStore":{"currentPageName":"quote", ...
```

After
```
> root.App || (root.App = {});
> root.App.now = 1671275144853;
> root.App.main = {"context":{"dispatcher":{"stores":"U2FsdGVkX18NwmzwZgyLozYcI3uwl2EXN\u002FWBnsSt9vGtBRZGAIiUIqV9mS1LKBRe42L1I1VjxC1qsKQ9g8KP4qeGBkrL28E0AG14...
```

**Comment by Rogach** [comment] 2022-12-17 13:55
They are encrypting the store data (it seems with AES) using `crypto-js` library.

Deobfuscated code is doing something like this:

```
var key = PBKDF2.create({ keySize: 8 }).compute(t._cs, JSON.parse(t._cr))
var plaintext = AES.decrypt("U2FsdGVk...", key)
var decoded = JSON.parse(decodeURIComponent(plaintext)
```

I'll continue deobfuscation, it seems I will be able to provide some working code sample soon.

**Comment by ValueRaider** [comment] 2022-12-17 14:06
Thanks @Rogach .

Any thoughts why they did this? Trying to block scraping? I'm wary of "biting the hand that feeds".

**Comment by Rogach** [comment] 2022-12-17 14:12
Who knows. Maybe it's an attempt to make scraping a bit harder. Maybe it's just a configuration change.

> If they wanted to stop scraping then why not just remove that data instead of encrypting?

They can't, because they still want to show the data to the site visitors.

**Comment by Rogach** [comment] 2022-12-17 14:36
Here's the fully working example. Runs in NodeJS, has a dependency on `crypto-js` library.

```js
var fs = require("fs");
var CryptoJS = require("crypto-js");

// replace the values with fresh values from root.App.main
var _cs = '7758ce68c359';
var _cr = '{"words":[1750977242,1882992877,448740864,329742483],"sigBytes":16}';
// place the root.App.main.context.dispatcher.stores into encrypted-stores.txt file
var stores = fs.readFileSync("encrypted-stores.txt", "utf8");

var key = CryptoJS.algo.PBKDF2.create({ keySize: 8 }).compute(_cs, JSON.parse(_cr)).toString();
var plaintext = CryptoJS.AES.decrypt(stores, key);
var decoded = JSON.parse(decodeURIComponent(escape(CryptoJS.enc.Latin1.stringify(plaintext))));

console.log(decoded);
```

I have to run now, don't have the time to convert this to python, sorry.

**Comment by ValueRaider** [comment] 2022-12-17 14:37
I meant they could drop the embedded JSON and just return HTML tables. HTML is a pain to parse, maybe worse than decoding the JSON.

**Comment by ValueRaider** [comment] 2022-12-17 17:40
I tried to port but give up. None of the examples I found use a "words" array as the salt, they all assume the salt is embedded in the encrypted text. [Example](https://devpress.csdn.net/python/630460127e6682346619ab98.html)

**Comment by onesoned** [comment] 2022-12-17 18:46
https://github.com/ranaroussi/yfinance/issues/1251#issue-1501456520

For some tickers (like SRAD or HIVE) the info-scraping is working...

**Comment by BiggRanger** [comment] 2022-12-17 18:57
I noticed this issue in my weekly Friday scrape (2022-12-16), it looks like at around 18:00 EST the Yahoo API changed and broke yfinance.

**Comment by ValueRaider** [comment] 2022-12-17 19:32
For any crypto experts that are unsure where to put decryption code, see `data.py get_json_data_stores()`, you can see where `root` element is accessed.

**Comment by tkarljws** [comment] 2022-12-17 21:39
I am getting the same results when trying to pull anything from the .info method.  I am only getting these results:

{'regularMarketPrice': None, 'preMarketPrice': None, 'logo_url': '', 'trailingPegRatio': 2.2022}

**Comment by toudyn** [comment] 2022-12-18 00:24
I tried using requests to see what was returned with the scraping url, eg. `requests.get('https://finance.yahoo.com/quote/SHEL.L')`, but am getting a 404 when I run that. Accessing that through browser and curl works just fine though.

**Comment by paulmcq** [comment] 2022-12-18 02:28
Since browser and curl work, is it maybe wanting a different UserAgent???

**Comment by robertluisw** [comment] 2022-12-18 05:47
Not to keep saying the same thing as others, but I'm having the same problem as well.  I really hope yahoo hasn't blocked scraping, they're like one of the last sources available. Is yFinance done for? I use this module everyday...

it scrapes, but only a few fields for me:
`>>> import yfinance as yf
>>> yf.Ticker('penn').info
{'regularMarketPrice': None, 'preMarketPrice': None, 'logo_url': '', 'trailingPegRatio': None}
>>> yf.Ticker('penn').info['regularMarketPrice']
>>> test = yf.Ticker('penn').info['regularMarketPrice']
>>> print(test)
None
>>> test2 = yf.Ticker('penn').info['previousClose']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'previousClose'
>>> tsla = yf.Ticker("TSLA")
>>> tsla.info
{'regularMarketPrice': None, 'preMarketPrice': None, 'logo_url': '', 'trailingPegRatio': 1.3152}`

**Comment by Rogach** [comment] 2022-12-18 06:59
Here's the sample decoder ported to Python:

```python
from pathlib import Path
import hashlib
import json
from base64 import b64decode
from Crypto.Cipher import AES
from Crypto.Util.Padding import unpad

stores = Path("encrypted-stores.txt").read_text()
_cs = '7758ce68c359'
_cr = '{"words":[1750977242,1882992877,448740864,329742483],"sigBytes":16}'

_cr = b"".join(int.to_bytes(i, length=4, byteorder="big") for i in json.loads(_cr)["words"])
password = hashlib.pbkdf2_hmac("sha1", _cs.encode("utf8"), _cr, 1, dklen=32).hex()

stores = b64decode(stores)
assert stores[0:8] == b"Salted__"
salt = stores[8:16]
stores = stores[16:]

def EVPKDF(
    password,
    salt,
    keySize=32,
    ivSize=16,
    iterations=1,
    hashAlgorithm="md5",
) -> tuple:
    """OpenSSL EVP Key Derivation Function
    Args:
        password (Union[str, bytes, bytearray]): Password to generate key from.
        salt (Union[bytes, bytearray]): Salt to use.
        keySize (int, optional): Output key length in bytes. Defaults to 32.
        ivSize (int, optional): Output Initialization Vector (IV) length in bytes. Defaults to 16.
        iterations (int, optional): Number of iterations to perform. Defaults to 1.
        hashAlgorithm (str, optional): Hash algorithm to use for the KDF. Defaults to 'md5'.
    Returns:
        key, iv: Derived key and Initialization Vector (IV) bytes.

    Taken from: https://gist.github.com/rafiibrahim8/0cd0f8c46896cafef6486cb1a50a16d3
    OpenSSL original code: https://github.com/openssl/openssl/blob/master/crypto/evp/evp_key.c#L78
    """

    assert iterations > 0, "Iterations can not be less than 1."

    if isinstance(password, str):
        password = password.encode("utf-8")

    final_length = keySize + ivSize
    key_iv = b""
    block = None

    while len(key_iv) < final_length:
        hasher = hashlib.new(hashAlgorithm)
        if block:
            hasher.update(block)
        hasher.update(password)
        hasher.update(salt)
        block = hasher.digest()
        for _ in range(1, iterations):
            block = hashlib.new(hashAlgorithm, block).digest()
        key_iv += block

    key, iv = key_iv[:keySize], key_iv[keySize:final_length]
    return key, iv

key, iv = EVPKDF(password, salt, keySize=32, ivSize=16, iterations=1, hashAlgorithm="md5")

cipher = AES.new(key, AES.MODE_CBC, iv=iv)
plaintext = cipher.decrypt(stores)
plaintext = unpad(plaintext, 16, style="pkcs7")
decoded = json.loads(plaintext)

print(decoded.keys())
```

**Comment by Korach250** [comment] 2022-12-18 07:24
Thanks. 
Continuing #1248 here. 
'floatShares' seems to be the issue.

1) It is curious that SOME data still gets through.
With these three tickers, TISI (Float 27,595,853), PASG (Float 27,502,482), SQL (Float 4,578,990)  my program runs perfectly (as it has run - systematically - for the last year).

2) However, with any other tickers' data, while it starts fine:
Data Downloaded

My program follows:
flt_shares = {}
flt_shares[f'{symbol}'] = ticker.info.get('floatShares')
df['Float'] = (flt_shares[f'{symbol}'])

Then when I try to put it in a dataframe with some formatting, it highlights an issue with the Float data:
df.loc[:, 'Float_'] = df['Float'].map('{:,.0f}'.format)
TypeError: unsupported format string passed to NoneType.__format__

**Comment by Rogach** [comment] 2022-12-18 08:00
@ValueRaider Seems I have a solution in PR #1253

**Comment by Korach250** [comment] 2022-12-18 18:21
Big thank you. [fredrik-corneliusson](https://github.com/fredrik-corneliusson)
Super newbie. I am doing it wrong because I go this.

ERROR: Could not find a version that satisfies the requirement yfinance-tz-cache (from versions: none)
ERROR: No matching distribution found for yfinance-tz-cache

%pip install yfinance-tz-cache
import yfinance as yf

**Comment by ValueRaider** [comment] 2022-12-18 19:59
@Korach250 Not everything on GitHub is also available on pypi.org

**Comment by fredrik-corneliusson** [comment] 2022-12-18 21:44
> Big thank you. [fredrik-corneliusson](https://github.com/fredrik-corneliusson) Super newbie. I am doing it wrong because I go this.
> 
Thanks, but you should really thank @Rogach, who did the investigation and coming up with a working Python solution.
My branch was referred by mistake, you should probably use the branch from @Rogach PR https://github.com/ranaroussi/yfinance/pull/1253
Or wait for it to be merged into yfinance.

**Comment by ValueRaider** [comment] 2022-12-18 21:47
New release out that fixes this - 0.1.92

**Comment by Korach250** [comment] 2022-12-18 22:00
First time I have ever seen the open source collaboration process in action. 
Powerful. 
Thanks all. Especially [@Rogach](https://github.com/Rogach)

**Comment by ValueRaider** [comment] 2022-12-18 22:09
> Only thing which i recognized which was not working for me, was that i was not able to get the number of shares.

Good spot. I can fix this.

**Comment by Korach250** [comment] 2022-12-18 22:10
Still stuck.

Same 'shareFloat' issue. Even though:
Successfully installed cryptography-38.0.4 yfinance-0.1.92

**Comment by ValueRaider** [comment] 2022-12-18 22:18
New release 0.1.93, fixes `Ticker.shares`

**Comment by saviornt** [comment] 2022-12-18 22:31
Just installed 0.1.93 and it looks like I'm having the same issue as 0.1.90 with Ticker.info

**Comment by ValueRaider** [comment] 2022-12-18 22:37
@saviornt Can you double-check, then post sample code? Is working for me.

**Comment by saviornt** [comment] 2022-12-18 22:42
Sure!
Here is the terminal output from using : Successfully installed cffi-1.15.1 cryptography-38.0.4 pycparser-2.21 yfinance-0.1.93

my code:

```
ticker = "AAPL"
yf_ticker = yf.Ticker(ticker)
info = yf_ticker.info  # Returns a dictionary of values for the security
df = pd.DataFrame.from_dict(info, orient="index")
df = df.rename(columns={0: ticker})
```

the info dictionary returns:

> {'regularMarketPrice': None,
>  'preMarketPrice': None,
>  'logo_url': '',
>  'trailingPegRatio': 2.6609}

and the dataframe returns:

> column = 'AAPL'
> index = 'regularMarketPrice', 'preMarketPrice', 'logo_url', 'trailingPegRatio'

the DF values are of course the dictionary values.

**Comment by saviornt** [comment] 2022-12-18 22:44
> Sure! Here is the terminal output from using : Successfully installed cffi-1.15.1 cryptography-38.0.4 pycparser-2.21 yfinance-0.1.93
> 
> my code:
> 
> ```
> ticker = "AAPL"
> yf_ticker = yf.Ticker(ticker)
> info = yf_ticker.info  # Returns a dictionary of values for the security
> df = pd.DataFrame.from_dict(info, orient="index")
> df = df.rename(columns={0: ticker})
> ```
> 
> the info dictionary returns:
> 
> > {'regularMarketPrice': None,
> > 'preMarketPrice': None,
> > 'logo_url': '',
> > 'trailingPegRatio': 2.6609}
> 
> and the dataframe returns:
> 
> > column = 'AAPL'
> > index = 'regularMarketPrice', 'preMarketPrice', 'logo_url', 'trailingPegRatio'
> 
> the DF values are of course the dictionary values.

Sure!
Here is the terminal output from using : Successfully installed cffi-1.15.1 cryptography-38.0.4 pycparser-2.21 yfinance-0.1.93

my code:

ticker = "AAPL"
yf_ticker = yf.Ticker(ticker)
info = yf_ticker.info  # Returns a dictionary of values for the security
df = pd.DataFrame.from_dict(info, orient="index")
df = df.rename(columns={0: ticker})
the info dictionary returns:

{'regularMarketPrice': None,
'preMarketPrice': None,
'logo_url': '',
'trailingPegRatio': 2.6609}

and the dataframe returns:

column = 'AAPL'
index = 'regularMarketPrice', 'preMarketPrice', 'logo_url', 'trailingPegRatio'

the DF values are of course the dictionary values.

**Comment by ValueRaider** [comment] 2022-12-18 22:47
What does this return? `yf.__version__`

If that returns 0.1.93, then confirm that PIP installed correct files - is "cryptography" in `site-packages/yfinance/utils.py`? Use `print(yf)` to show where PIP installed code.

**Comment by galashour** [comment] 2022-12-18 22:48
I took the first few lines above:

ticker = "AAPL"
yf_ticker = yf.Ticker(ticker)
info = yf_ticker.info # Returns a dictionary of values for the security

when I then do:
print(info)

I do get the data (maybe something gets mixed up during the conversion to dataframe, but the dict itself seems to be populated with the right data).

**Comment by saviornt** [comment] 2022-12-18 22:52
@ValueRaider I think I found the problem! yf.__version__ is returning 0.1.90.

**Comment by Korach250** [comment] 2022-12-19 00:09
Great @ValueRaider. Much better. However...
, my scan was happy again till it reached AVCO, where it produced an error I have never seen before:
KeyError: 'QuoteSummaryStore'. 
Is this systemic, or should I write an exception?

**Comment by prolexgreen** [comment] 2022-12-19 02:56
I am also facing this problem, 
Using PANDAS datareader and getting "Exception in Tkinter callback"

**Comment by havedill** [comment] 2022-12-19 10:25
Thanks for all the hard work guys. 0.1.93 confirmed behaving the same as prior

**Comment by t1b8** [comment] 2022-12-19 16:53
Hello, I could make use of the help of more experienced people. I cannot retrieve info anymore, typically I get {'regularMarketPrice': None, 'preMarketPrice': None, 'logo_url': '', 'trailingPegRatio': 2.164}. I tried to update yfinance to 0.1.93 using pip install yfinance --upgrade --no-cache-dir but only 0.1.87 was installed. I thank you in advance for your assistance.

**Comment by EverAzureRest** [comment] 2022-12-19 17:04
Was having the same problem as others (no info on the ticker obj), installed 0.1.94 via pip and everything is working again.  Thanks to all for their hard work in releasing a fix so quickly!

**Comment by MacDeer** [comment] 2022-12-19 17:07
Can you tell me which command you used to install 0.1.94 via pip. May thanks in advance

**Comment by MacDeer** [comment] 2022-12-19 17:22
it doesn't update it. It says
Requirement already satisfied: yfinance in /usr/local/lib/python3.6/dist-packages (0.1.87)

**Comment by EverAzureRest** [comment] 2022-12-19 17:24
> python3.6
 
I think you need to update your python environment.  It's working in 3.10

**Comment by ValueRaider** [comment] 2022-12-19 17:51
This is the wrong place for PIP issues. [Try here](https://googlethatforyou.com?q=pip%20not%20updating%20package)

**Comment by fredrik-corneliusson** [comment] 2022-12-19 23:01
@ValueRaider Regarding the backport to the 0.1 branch.
I think 0.1 branch should be deprecated as soon as possible and use of it discouraged.

Just did a quick check and the amount of unnecessary request it makes to get the same information as 0.2 branch could be the cause of yahoo trying to make scraping harder.
Especially the request to the html page that that is not intended a a API.
Test code:
```
ticker = yf.Ticker("GOOGL")
ticker.earnings
```

Running the test to just get earnings with 0.1.94:
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/holders HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query1.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query1.finance.yahoo.com:443 "GET /ws/fundamentals-timeseries/v1/finance/timeseries/GOOGL?symbol=GOOGL&type=trailingPegRatio&period1=1655762087&period2=1671576887 HTTP/1.1" 200 363
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/financials HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/analysis HTTP/1.1" 200 None
Ran 1 test in 11.922s
```

And the 0.2 branch:
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/financials HTTP/1.1" 200 None
Ran 1 test in 1.623s
```

Keep in mind the https://finance.yahoo.com/quote/ html/{ticker} page is very heavy on data (megabytes).
I'm afraid keeping the 0.1 branch and especially after yahoo made it harder to scrape could just trigger more actions from yahoo to limit access even more, effectively shutting down yfinance as a project.

**Comment by ValueRaider** [comment] 2022-12-19 23:08
@fredrik-corneliusson Very good point. I'll send out now, I'm happy with 0.2

**Comment by fredrik-corneliusson** [comment] 2022-12-19 23:13
Great thanks @ValueRaider!

**Comment by galashour** [comment] 2022-12-19 23:47
> @fredrik-corneliusson Very good point. I'll send out now, I'm happy with 0.2

I get this with 0.2.1:
Traceback (most recent call last):
  File "C:\Data\Python\Pumba\Pumba_fetch_data.py", line 657, in get_ticker_data
    df_quarterly_financials = ticker_data.quarterly_financials
AttributeError: 'Ticker' object has no attribute 'quarterly_financials'

**Comment by ValueRaider** [comment] 2022-12-20 00:00
@galashour Put that in a new issue. Btw you can workaround by switching to `income_stmt`, `balancesheet` & `cashflow`

**Comment by prolexgreen** [comment] 2022-12-20 01:05
I am still gettings errors

**Comment by ValueRaider** [comment] 2022-12-20 12:02
@Travis-Barton good point. I've restored the `balancesheet` API and added a small summary changelog near top of README

**Comment by LouviersJ** [comment] 2022-12-22 06:38
.quarterly_cashflow is not working for some stocks including but not limited to AMAM
META, FBSE, MVO, OSG, EPM, FFIE, ELYS, JWEL, MMU, IHD
I included a few that I found so maybe you could find the common denominator...
Currently a line such as yf.Ticker('AMAM').quarterly_cashflow isn't even returning an empty dataframe, I am getting no output.

**Comment by galashour** [comment] 2022-12-22 07:59
> .quarterly_cashflow is not working for some stocks including but not limited to AMAM META, FBSE, MVO, OSG, EPM, FFIE, ELYS, JWEL, MMU, IHD I included a few that I found so maybe you could find the common denominator... Currently a line such as yf.Ticker('AMAM').quarterly_cashflow isn't even returning an empty dataframe, I am getting no output.

Did a quick check on my side, with version 0.2.3:
for tickers: META, OSG, EPM, FFIE, ELYS 
I was able to get dataframe by doing: (where XXXX is one of the above tickers):
  yf.Ticker(XXXX).quarterly_cashflow
  
for tickers JWEL, AMAM, FBSE, MMU, IHD - indeed I got back an empty dataframe, but checking on yahoo, the quarterly data was missing as well, see for example (make sure you switch to the quarterly view):
https://finance.yahoo.com/quote/AMAM/cash-flow?p=AMAM
It seems that for these tickers yahoo currently doesn't have the quarterly data.

**Comment by ValueRaider** [comment] 2022-12-22 09:48
> .quarterly_cashflow is not working for some stocks including but not limited to AMAM
> META, FBSE, MVO, OSG, EPM, FFIE, ELYS, JWEL, MMU, IHD

@LouviersJ @galashour can we move this to a separate issue please. I can pin it, and there is a solution.

This is where the new `legacy` argument comes in, because the old table formats do have quarterlies - `Ticker.get_cashflow(freq="quarterly", legacy=True)`. This is mentioned in README. Am open to alternative API suggestions.

**Comment by galashour** [comment] 2022-12-22 15:25
> > .quarterly_cashflow is not working for some stocks including but not limited to AMAM
> > META, FBSE, MVO, OSG, EPM, FFIE, ELYS, JWEL, MMU, IHD
> 
> @LouviersJ @galashour can we move this to a separate issue please. I can pin it, and there is a solution.

sure. I agree would be easier to track on a separate issue. I'll let @LouviersJ do so, since he is the originator of the issue.

I'll just add that I'm not 100% sure there is an issue though, since one some of the mentioned tickers I was able to get the data (with the updated release), and for the others - the data seems to be missing also on the yahoos site once switching to the quarterly view.

**Comment by ValueRaider** [comment] 2022-12-22 15:50
For these tickers can still get the old quarterly tables filled with valid data. That's why I want to pin it.

**Comment by galashour** [comment] 2022-12-22 15:55
done #1265

**Closed** 2023-01-06 23:20 UTC

**Comment by hculver** [comment] 2023-02-20 11:41
> @Rogach, after examining the sample js and python code in Dec 18th post, and a representative data file, I was able to find my particular instance of  the _cs value following the root.App.Now.  But I was not able to locate anything resembling the 'words' used in the _cr variable.  Per the comment I was expecting these values expected to be in the raw html file.  I looked in the header as well as in and around the json, but they were not readily apparent.  Where are these words in the html file?

**Comment by Rogach** [comment] 2023-02-20 12:17
@hculver Dec 18th was a long time ago, the structure of the data changed a lot since then. See #1407 for newer discussion.
