### ISSUE TITLE
Compatibilty with Python 3.10.2

### ISSUE THREAD

**Issue by TheRobinLu** [ranaroussi/yfinance#940] opened 2022-01-24 22:00 UTC
Just upgrade Python to 3.10.02, when downloaded data, got following error.
yf.download('AMD', interval="1d", start="2021-01-11", group_by="ticker")

Exception in thread Thread-1 (_run_via_pool):
Traceback (most recent call last):
  File "C:\Users\lurob\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\lurob\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Project\Python\Test310\venv\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "E:\Project\Python\Test310\venv\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "E:\Project\Python\Test310\venv\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "E:\Project\Python\Test310\venv\lib\site-packages\yfinance\base.py", line 295, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

any advise?

**Comment by moshfrid** [comment] 2022-01-24 22:12
The issue isn't python, it's pandas 1.4, duplicate of #939

**Comment by aaronweewee** [comment] 2022-01-28 11:48
This is a problem with python 3.10 as well. When I downgraded Pandas to 1.3.5 it still had the same error. Downgrading both python and pandas solved it

**Comment by ValueRaider** [comment] 2022-10-28 13:43
This was fixed soon after reporting: https://github.com/ranaroussi/yfinance/issues/937#issuecomment-1025131425

**Closed by ValueRaider** 2022-10-28 13:43 UTC
Labels: yf-prices
