### ISSUE TITLE
ticker_object.income_stmt not working for days

### ISSUE THREAD

**Issue by LoreBell96** [ranaroussi/yfinance#1481] opened 2023-04-04 19:22 UTC
Hi All,

I'm trying to use ticker_object.income_stmt for several days now, but I've got the following error message

   CE = ticker_object.income_stmt
         ^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: yfinance failed to decrypt Yahoo data response

how can I fix it? 

thank you in advance

**Comment by homerokzam** [comment] 2023-04-06 19:27
What version of pandas are you using?

**Comment by ValueRaider** [comment] 2023-04-06 21:05
@homerokzam Pandas nothing to do with this issue.

Duplicate of #1407

**Closed by ValueRaider** 2023-04-06 21:05 UTC
