### ISSUE TITLE
Quarterly cashflow returns empty dataframe

### ISSUE THREAD

**Issue by LouviersJ** [ranaroussi/yfinance#1252] opened 2022-12-18 03:47 UTC
*I know this is a duplicate of issues #343 #328 but I see that some of the code was changed yesterday and was wondering if that is what caused this bug*
It appears .quarterly_cashflow is returning an empty dataframe. I tried uninstalling and reinstalling yfinance and a few other things and it didn't seem to work so that brought me here.

Example:
yf.Ticker('goog').quarterly_cashflow

Returns:
	Open	High	Low	Close	Adj Close	Volume
Date

**Comment by ValueRaider** [comment] 2022-12-18 12:04
Duplicate of #1246

**Closed by ValueRaider** 2022-12-18 12:04 UTC
