### ISSUE TITLE
0.2.39 introduces issues with `repair`

### ISSUE THREAD

**Issue by darth-veitcher** [ranaroussi/yfinance#1943] opened 2024-05-19 15:15 UTC
### Describe bug

Attempting to import package after installation with `yfinance[nospam,repair]` gives the following exception.

```
File "/usr/local/lib/python3.10/site-packages/yfinance/__init__.py", line 23, in <module>
    from .ticker import Ticker
  File "/usr/local/lib/python3.10/site-packages/yfinance/ticker.py", line 28, in <module>
    from .base import TickerBase
  File "/usr/local/lib/python3.10/site-packages/yfinance/base.py", line 40, in <module>
    from .scrapers.history import PriceHistory
  File "/usr/local/lib/python3.10/site-packages/yfinance/scrapers/history.py", line 1207
    logger.debug(f'price-repair-split: Splits: {str(df['Stock Splits'][split_f].to_dict())}')
                                                        ^^^^^
SyntaxError: f-string: unmatched '['
```

### Simple code that reproduces your problem

```zsh
python -m venv venv
source venv/bin/activate
python -m pip install "yfinance[nospam,repair]"
python -c 'import yfinance as yf;'
```

### Debug log

```
➜ python -c 'import yfinance as yf;'                                 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/venv/lib/python3.10/site-packages/yfinance/__init__.py", line 23, in <module>
    from .ticker import Ticker
  File "/private/tmp/venv/lib/python3.10/site-packages/yfinance/ticker.py", line 28, in <module>
    from .base import TickerBase
  File "/private/tmp/venv/lib/python3.10/site-packages/yfinance/base.py", line 40, in <module>
    from .scrapers.history import PriceHistory
  File "/private/tmp/venv/lib/python3.10/site-packages/yfinance/scrapers/history.py", line 1207
    logger.debug(f'price-repair-split: Splits: {str(df['Stock Splits'][split_f].to_dict())}')
                                                        ^^^^^
SyntaxError: f-string: unmatched '['
```

### `yfinance` version

0.2.39

### Python version

Python 3.10.12

### Operating system

MacOS

**Comment by eric-stanley** [comment] 2024-05-19 16:09
Tested and encountered the same issue

**yfinance version**
0.2.39

**Python version**
Python 3.11

**Operating system**
Pop OS

**Comment by ValueRaider** [comment] 2024-05-19 16:24
Duplicate of #1942

**Closed by ValueRaider** 2024-05-19 16:24 UTC
