### ISSUE TITLE
Inconsistent Adj Close for a ticker

### ISSUE THREAD

**Issue by Skumin** [ranaroussi/yfinance#1038] opened 2022-07-20 16:47 UTC
I've discovered an interesting bug (?) - there seems to be certain (small) randomness associated with the Adj Close column of the API (specifically `yf.download`) for a single ticker.

I'm running `yfinance` version 0.1.70 on Python 3.8.10.

Consider the code below:

```
from datetime import date
import numpy as np
import pandas as pd
import yfinance as yf

ticker = "ATVI"

prc = []

for i in range(100):
    ticker_equity = yf.download(ticker)
    ticker_equity.reset_index(inplace=True)
    ticker_equity["Date"] = ticker_equity["Date"].apply(lambda x: x.date())
    prc.append(ticker_equity[ticker_equity["Date"] == date(2017, 12, 21)]["Adj Close"].tolist()[0])

diffs = np.diff(prc)
min(diffs), max(diffs) # Should just be (0, 0)
```

On my machine, this code produces non-zero (and quite big, in absolute value) values on the last line. I can see why this is with a naked eye if I just print out `prc` - the values are different slightly. Is this perhaps related to https://github.com/ranaroussi/yfinance/issues/626?

**Comment by ValueRaider** [comment] 2022-07-20 18:00
I'm seeing tiny changes:

> (-1.1444091796875e-05, 1.1444091796875e-05)

What do you see?

I also can't reproduce https://github.com/ranaroussi/yfinance/issues/626 so unsure if related.

**Comment by Skumin** [comment] 2022-07-20 18:12
Yes, I see values in the same order of magnitude. I still don't understand why this would be though - wouldn't you expect a price in the past to be exactly the same always (until the next stock split), no matter when you run your code?

**Comment by ValueRaider** [comment] 2022-07-20 19:55
The prices _are_ exactly the same. The _adjusted_ price is changing, and in a consistently negligible way so first thought goes to floating-point rounding errors. This is possible depending on how adjustment calculation is structured.

The obvious approach is to use first ever price as base and adjust forward in time, as you are assuming. But what if Yahoo uses the price *now* as base? [This person thinks that's what they do](http://marubozu.blogspot.com/2006/09/how-yahoo-calculates-adjusted-closing.html). Then the first rounding error can vary and all subsequent calculations can vary slightly. I'm only surprised it got to 10^-5, would have expected below 10^-10.

**Closed** 2022-07-20 21:03 UTC
