### ISSUE TITLE
Scraper error "TypeError: string indices must be integers"  - Yahoo decrypt fail

### ISSUE THREAD

**Issue by SamZhang02** [ranaroussi/yfinance#1291] opened 2023-01-12 22:06 UTC
### 2023 January 13
By the time of posting the issue (2023 January 12), the issue only occured sometimes. The library is now (2023 January 13) completely broken and I am unable to retrieve any stock informatio
### 2023 January 14
Fix has been merged to the branch `dev`

## Info about your system:
yfinance version: 0.2.3
Operating system: macOS Monteray 12.0.1
### Snippet that can recreate the error
```
stock = yf.Ticker("^GSPC")
info = stock.info
```
## Error
Message:`TypeError: string indices must be integers`
It seems to be a problem where the scraper is not scraping the correct information, leading to a crash.
### Traceback:
```
Traceback (most recent call last):
  File "/home/2022/szhang139/.local/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/2022/szhang139/repos/STONK/src/main.py", line 61, in notify
    market = get_major_index(f'Market Close - {daytime.today_date()}')
  File "/home/2022/szhang139/repos/STONK/src/market_info.py", line 63, in get_major_index
    sp500 = get_stock('^GSPC')
  File "/home/2022/szhang139/repos/STONK/src/market_info.py", line 41, in get_stock
    stock_info = get_stock_info(stock_name)
  File "/home/2022/szhang139/repos/STONK/src/market_info.py", line 8, in get_stock_info
    info = stock.info
  File "/home/2022/szhang139/.local/lib/python3.10/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/home/2022/szhang139/.local/lib/python3.10/site-packages/yfinance/base.py", line 894, in get_info
    data = self._quote.info
  File "/home/2022/szhang139/.local/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 27, in info
    self._scrape(self.proxy)
  File "/home/2022/szhang139/.local/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 58, in _scrape
    quote_summary_store = json_data['QuoteSummaryStore']
```
### Frequency
The error occurs in no apparent pattern. Every time it occurs, it seem to persist for some range of time before it recovers back to normal.
n.

**Comment by Lokan0py** [comment] 2023-01-13 08:39
I also have the exact same problem as you, good to know that im not alone. The yfinance ticker module seems very unstable at the moment.

**Comment by YieldPilot** [comment] 2023-01-13 11:57
Same issue here.

Traceback (most recent call last):
  File "/home/gulder/PycharmProjects/YPUpdater/YPFunctions.py", line 171, in updatepricedata
    beta = yf.Ticker(ticker).info.get('beta')
  File "/home/gulder/PycharmProjects/YPUpdater/venv/lib/python3.8/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/home/gulder/PycharmProjects/YPUpdater/venv/lib/python3.8/site-packages/yfinance/base.py", line 894, in get_info
    data = self._quote.info
  File "/home/gulder/PycharmProjects/YPUpdater/venv/lib/python3.8/site-packages/yfinance/scrapers/quote.py", line 27, in info
    self._scrape(self.proxy)
  File "/home/gulder/PycharmProjects/YPUpdater/venv/lib/python3.8/site-packages/yfinance/scrapers/quote.py", line 58, in _scrape
    quote_summary_store = json_data['QuoteSummaryStore']
TypeError: string indices must be integers

**Comment by ValueRaider** [comment] 2023-01-13 12:41
Are you accessing `info` in a loop of many tickers? Spamming `info` is a great way to get temporarily blocked, which I suspect.

If yes, what key are you accessing? Might be better way to get data.

**Comment by andreasklippinge** [comment] 2023-01-13 12:46
> Are you accessing `info` in a loop of many tickers? Spamming `info` is a great way to get temporarily blocked, which I suspect.
> 
> If yes, what key are you accessing? Might be better way to get data.

I have the same error, and it does not matter if I looping through 4 or 503 stocks.. 
```
data = yf.download(tickers, period = "max", interval = "1mo", progress=True)
stocks = []
for ticker in tickers:
    df = data.xs(ticker, level=1, axis=1).copy()
    df.dropna(inplace=True)
    if df.empty:
        continue
    info = yf.Ticker(ticker).info
    div = info.get("dividendYield")  
    mcap = info.get("marketCap") 
    PE = info.get("trailingPE")
    if div is not None and div >= 0.04 and mcap is not None and mcap > 1E10 and PE is not None and PE < 15:
        stocks.append(ticker)
```
```
Traceback (most recent call last):

  File "C:\Users\untitled0.py", line 18, in <module>
    info = yf.Ticker(ticker).info

  File "C:\Users\Andreas\anaconda3\lib\site-packages\yfinance\ticker.py", line 138, in info
    return self.get_info()

  File "C:\Users\Andreas\anaconda3\lib\site-packages\yfinance\base.py", line 894, in get_info
    data = self._quote.info

  File "C:\Users\Andreas\anaconda3\lib\site-packages\yfinance\scrapers\quote.py", line 27, in info
    self._scrape(self.proxy)

  File "C:\Users\Andreas\anaconda3\lib\site-packages\yfinance\scrapers\quote.py", line 58, in _scrape
    quote_summary_store = json_data['QuoteSummaryStore']

TypeError: string indices must be integers
```

**Comment by CopenhagenToLondon** [comment] 2023-01-13 12:54
Yes me too. It seems it went down hill over the last few moments. I can now only run about 1 at a time.
I get the error on financials with some symbols and on balancesheet data with other symbols, but none on price data or dividends

**Comment by YieldPilot** [comment] 2023-01-13 12:59
> 

Yes, I am, loop of around 450 tickers.
I am accessing:
yf.Ticker(ticker).info.get('beta') and
yf.Ticker(ticker).info.get('dividendRate')

**Comment by galashour** [comment] 2023-01-13 13:03
Indeed, I also just encountered the same thing. 
In the specific tool, I'm suing it for a single ticker, and  I get this issue as well

`# Retrieve fundamental and technical data from yfinance
        ticker_data = yf.Ticker(ticker)
        time.sleep(2)  # just added today, doesn't help
        ticker_info = ticker_data.info`

I tried adding sleep, but it didn't help either.

The weird part, is that when I write the code line by line in the Python Console (pycharm) it worked, but now even (changed in the past 20 minutes or so), I get ticker_info = None also in the console.

**Comment by AnubisSg1** [comment] 2023-01-13 13:10
Same failure, im def not ip blocked and didn't spam. It started yesterday and today I get the same failure the whole time

**Comment by chris-hmmr** [comment] 2023-01-13 13:22
I believe the cause of this relates to the underlying data structure this library scrapes from [Yahoo Finance](https://finance.yahoo.com/) has changed. They introduced encryption on the ticker data before the turn of the year, which was fixed, and this time they changed the parameters around the encryption.

**Comment by ValueRaider** [comment] 2023-01-13 13:55
In case it helps, these were the decryption params Yahoo was providing:
```
_cs = '3b1885bff81b'
_cr = {"words":[1975313454,-1113096907,-1675002031,-87263202], "sigBytes":16}
```

**Comment by ovisimon** [comment] 2023-01-13 14:01
This was working for me about an hour ago, and all of a sudden it stopped. It throws some error about the indeces needing to be integers:
```
import yfinance as yf
msft = yf.Ticker("MSFT")
print(msft.cashflow) 
```

**Comment by ammarhaiderak** [comment] 2023-01-13 14:25
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-9-2b7dfee1989e>](https://localhost:8080/#) in <module>
     13 # 3mo => 2h, 4h, 12h, use 1h interval for this
     14 
---> 15 df = df.ta.ticker("TSLA", interval='1m')
     16 
     17 

5 frames
[/usr/local/lib/python3.8/dist-packages/yfinance/scrapers/quote.py](https://localhost:8080/#) in _scrape(self, proxy)
     56         json_data = self._data.get_json_data_stores(proxy=proxy)
     57         try:
---> 58             quote_summary_store = json_data['QuoteSummaryStore']
     59         except KeyError:
     60             err_msg = "No summary info found, symbol may be delisted"

TypeError: string indices must be integers
```

getting this issue on every symbol. Seems to be broken. Any workaround ?

**Comment by ValueRaider** [comment] 2023-01-13 15:24
Where Yahoo used to provide the decryption parameters, there is this new key-value:
```
'93634354fa08860f003e': '4f566bf243f93d68718581c573aee0ff86456eef74bf9c33244c765b6ae2470059db233bf70a4fb3c16c24047befc4e993e717df7cbd4f1bebddb9649abdf5e3'
```
Any ideas?

**Comment by pombears** [comment] 2023-01-13 16:26
Occurring for me to.

security = yf.Ticker(ticker)

The object gets returned from doing above and can return list of attributes no problem with print(security.__dir__())

Below normally works for pulling out any information from the 'balance_sheet' dataframe or 'info' dictionary of the instance:
print(security.info)
print(balance_sheet)

Instead consistently getting below error on these:
TypeError: string indices must be integers, not 'str'

Happening for both single calls to yf.Ticker(ticker) and in loop.

**Comment by 25shmeckles** [comment] 2023-01-13 16:28
I am having the same problem. Weird enough, the query URL works if loaded via the browser but not if queried via Python. It looks like Yahoo is actively blocking non-browser queries.

**Comment by bruce1095** [comment] 2023-01-13 16:45
A possible solution to this issue would be to:

*Verify that the correct key and ciphertext are being used for decryption.
*Check if the key and ciphertext are getting passed correctly to the decryption function.
*Make sure that the key and ciphertext are in the correct format and length for the decryption algorithm being used.
*Verify that the decryption algorithm is implemented correctly and that there are no bugs in the code.
*Check the encryption algorithm that is used to encrypt the data, maybe the algorithm has been changed and the decryption algorithm is not compatible with the new encryption algorithm.
*If the above steps don't solve the problem, try using a different decryption algorithm and see if that resolves the issue.
*It's important to keep in mind that the key and ciphertext must match the encryption algorithm. Also, encrypting and decrypting the data with a different algorithm than what it was encrypted with will cause issues.

**Comment by bruce1095** [comment] 2023-01-13 16:47
Based on the information provided, it appears that the issue is related to a change in the data format or method of accessing the data from the Yahoo Finance API. Instead of providing the decryption parameters, the data is now being returned in a key-value format, where the key is a string of characters and the value is a string of hexadecimal characters.

A possible solution to this issue would be to:

Check the documentation of the Yahoo Finance API to see if there have been any recent changes to the data format or method of accessing the data.
Check if there is any new endpoint to fetch the data.
Check if there is any new package or library that can be used to fetch the data.
If the above steps don't provide any information, try contacting Yahoo Finance customer support for help in understanding and working with the new data format.
If none of the above steps work, you may have to look for an alternative data source or a different way to get the data you need.
It is possible that the key and value you provided is a token and an encrypted version of a token. To know for sure, you need to check with Yahoo finance documentation or developer community.

**Comment by ValueRaider** [comment] 2023-01-13 17:13
@bruce1095 That's a lot of words to contribute nothing useful. ChatGPT?

**Comment by ammarhaiderak** [comment] 2023-01-13 17:47
Meanwhile we can use this API.
`
def yfinanceDataframe(symbol, interval, _range):  
  headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}

  data = requests.get(f'https://query1.finance.yahoo.com/v8/finance/chart/{symbol}?interval={interval}&range={_range}', headers=headers).json()
  timestamp = data['chart']['result'][0]['timestamp']
  data = data['chart']['result'][0]['indicators']['quote'][0]


  df = pd.DataFrame(data)
  df['Datetime'] = timestamp
  df['Datetime'] = df['Datetime'].apply(lambda x: dt.fromtimestamp(x).strftime('%m/%d/%Y %H:%M'))
  df.dropna(inplace=True)
  df.reset_index(inplace=True)
  df.rename(columns={'close': 'Close'}, inplace=True)

  return df
`

**Comment by bruce1095** [comment] 2023-01-13 17:50
Yes, ChatGPT. SorrySent from my iPhoneOn Jan 13, 2023, at 9:13 AM, ValueRaider ***@***.***> wrote:﻿
@bruce1095 That's a lot of words to contribute nothing useful. ChatGPT?

**Comment by alexa-infra** [comment] 2023-01-13 19:18
I think `93634354fa08860f003e` key/value will change with time..

             encrypted_stores = data['context']['dispatcher']['stores']
    -        _cs = data["_cs"]
    -        _cr = data["_cr"]
    -
    -        _cr = b"".join(int.to_bytes(i, length=4, byteorder="big", signed=True) for i in json.loads(_cr)["words"])
    -        password = hashlib.pbkdf2_hmac("sha1", _cs.encode("utf8"), _cr, 1, dklen=32).hex()
    +        password_key = next(key for key in data.keys() if key not in ["context", "plugins"])
    +        password = data[password_key]
 
             encrypted_stores = b64decode(encrypted_stores)

and it seems this

    -    plaintext = unpad(plaintext, 16, style="pkcs7")
    +    plaintext = unpad(plaintext, 128, style="pkcs7")

**Comment by jjwjj** [comment] 2023-01-13 21:00
I get the same error. Tested individual tickers, and ran tests from several different IP addresses.

**Comment by romanchekashov** [comment] 2023-01-13 22:28
```
stock = yf.Ticker("^GSPC")
info = stock.info
```
Message: `TypeError: string indices must be integers`

How it can be fixed?

**Comment by idan6767** [comment] 2023-01-13 22:43
same here for me, cannot get .info from any stock i have tired for the last few days.

"    quote_summary_store = json_data['QuoteSummaryStore']
TypeError: string indices must be integers
"

**Comment by dschaefer** [comment] 2023-01-14 00:20
That is working for me though I had to leave the unpad block_size arg at 16 when using usePycryptodome. But also works without usePycryptodome.

**Comment by ValueRaider** [comment] 2023-01-14 00:40
Can you submit a pull request? If a Github newbie see #1084

**Comment by thejaxlee** [comment] 2023-01-14 06:37
Hi, I'm also impacted by this issue. 

Do I need to declare the encryption parameters within my script or do I need to download latest version of yfinance module?

**Comment by galashour** [comment] 2023-01-14 09:10
> Hi, I'm also impacted by this issue.
> 
> Do I need to declare the encryption parameters within my script or do I need to download latest version of yfinance module?

Everyone is impacted.
Per @ValueRaider request, no need to continue reporting the issue.

just continue tracking this thread, and when a new release with a fix is available/merged to main, a comment will be put in this thread and then we should be able to pip-install the new version.

The plan, similar to past cases, is that once a solution is available in the new release **no change** to the existing scripts will be required (or at least this is the motivation).

**Comment by james-stevens** [comment] 2023-01-14 14:52
I downloaded `yfinance` yesterday & it worked fine, so was planning on doing some work with it today, but today I get this error when running the most simple example code
```
#! /usr/bin/python3
import yfinance as yf
msft = yf.Ticker("MSFT")
msft.info
```
The error line is `quote_summary_store = json_data['QuoteSummaryStore']`

I looked at the value of `json_data` and it's a `base64` encoded binary object that starts with the string `Salted__`, which seems to be the data `decrypt_cryptojs_aes()` is looking for.

```
def decrypt_cryptojs_aes(data):
    encrypted_stores = data['context']['dispatcher']['stores']
    _cs = data["_cs"]
    _cr = data["_cr"]
```

The problem seems to be that `data['context']['dispatcher']['stores']` is present, but `_cs` and `_cr` are *NOT* present, so this `if` condition (in `data.py` is not triggering
```
        if "_cs" in data and "_cr" in data:
            data = decrypt_cryptojs_aes(data)
```
If I trigger the decrypt on the presence of `data['context']['dispatcher']['stores']` then it fails cos `_cs` and `_cr` are missing, but "critical".

I don't know what they used to look like, so I don't know what to look for in the data they do provide - so I'm not sure where to take this from here.

I tried using the mysterious hex strings, at the end of data, (mentioned earlier) directly as the `_cs` and `_cr` (both ways round) and it didn't work, for example
```
   "93634354fa08860f003e": "4f566bf243f93d68718581c573aee0ff86456eef74bf9c33244c765b6ae2470059db233bf70a4fb3c16c24047befc4e993e717df7cbd4f1bebddb9649abdf5e3"
```
Here I tried decoding the hex they provide & assigning the bytes to `_cs` and `_cr` (both ways round) and remove some of the decoding of `_cs` and `_cr`, but that didn't work either - again hard to know what to change without having seen what `_cs` and `_cr` looked like before.
```
        for x in data:
            last = x
            last_val = data[x]
        data["_cs"] = bytearray.fromhex(last)
        data["_cr"] = bytearray.fromhex(last_val)
```
```
    # _cr = b"".join(int.to_bytes(i, length=4, byteorder="big", signed=True) for i in json.loads(_cr)["words"])
    password = hashlib.pbkdf2_hmac("sha1", _cs, _cr, 1, dklen=32).hex()
```
(my code with some of the decoding removed, to use the bytes directly)

I think I hit a roadblock now - hope some of this helps

:(

**Comment by james-stevens** [comment] 2023-01-14 15:04
@alexa-infra patch also needs something like this, or the `decrypt_cryptojs_aes` doesn't trigger
```
176c178,180
<         data = decrypt_cryptojs_aes(data)
---
>
>         if "_cs" in data and "_cr" in data:
>             data = decrypt_cryptojs_aes(data)
```

**Comment by ValueRaider** [comment] 2023-01-14 15:04
PR #1297 seems to work. But before I merge & release, I want to make other changes to reduce Yahoo server load - see #1300 for discussion.

**Comment by ValueRaider** [comment] 2023-01-14 15:05
@james-stevens Please discuss the patch in it's pull request.

**Comment by cmjordan42** [comment] 2023-01-14 19:32
> PR #1297 seems to work. But before I merge & release, I want to make other changes to reduce Yahoo server load - see #1300 for discussion.

I'm not sure it makes sense to conflate the release of a critical fix with a potential efficiency improvement. 100% of the yfinance community will benefit from #1297 urgently being released.

**Comment by ValueRaider** [comment] 2023-01-14 19:51
I think it does make sense to conflate. Why is Yahoo encrypting this data? Is it to stop scraping because of the high server load? Then it's in our benefit to reduce load of `yfinance`. What will Yahoo do next?

Plus this will not delay much, most groundwork was done weeks-months ago.

**Comment by bruce1095** [comment] 2023-01-14 20:48
I would appreciate an expedited roll out. I use Yfinance pretty extensively and all my code is now defunct. Sent from my iPhoneOn Jan 14, 2023, at 11:52 AM, ValueRaider ***@***.***> wrote:﻿
I think it does make sense to conflate. Why is Yahoo encrypting this data? Is it to stop scraping because of the high server load? Then it's in our benefit to reduce load of yfinance. What will Yahoo do next?
Plus this will not delay much, most groundwork was done weeks-months ago.

**Comment by OhadPorat-2001** [comment] 2023-01-14 21:15
Look at dev changes and install it by pip install git+"http..."@dev

**Comment by HateAndLoveModding** [comment] 2023-01-14 22:04
It seems like the url is cut off. Could you please give the the full url? Thanks.

**Comment by ming-afk** [comment] 2023-01-14 22:23
pip install git+"https://github.com/ranaroussi/yfinance"@dev

>

**Comment by ValueRaider** [comment] 2023-01-14 23:03
PIP release out

**Comment by dannydoritoeth** [comment] 2023-01-14 23:36
It might be user error but I still get the same error using the normal pip install and also
 
!pip3 install git+"https://github.com/ranaroussi/yfinance"@dev

**Comment by ValueRaider** [comment] 2023-01-14 23:38
Don't mess with urls, just upgrade how you always do.

**Comment by dannydoritoeth** [comment] 2023-01-14 23:41
The google collab notebook I'm using has this in it and its still failing

!pip3 install yfinance

Would you expect that to be working now?

**Comment by interstormtech** [comment] 2023-01-14 23:45
Thank you very much - your time and expertise is appreciated by the community. I uninstalled and reinstalled latest...everything working perfectly! Again - many thanks!

**Comment by dannydoritoeth** [comment] 2023-01-15 00:17
Got it. It was just defaulting to the old version. This works:

!pip3 install yfinance==0.2.4

Thank you very much for the quick turn around.

**Comment by bruce1095** [comment] 2023-01-15 00:27
Everything’s working for me now. Thank you! Sent from my iPhoneOn Jan 14, 2023, at 3:39 PM, ValueRaider ***@***.***> wrote:﻿
Don't mess with urls, just upgrade how you always do.

**Comment by GPN87** [comment] 2023-01-15 02:24
Is there any reason why I would be getting a 'ModuleNotFoundError: No module named 'multitasking'" error? Multitasking, as well as yfinance 0.2.4 are both installed in my environment.

**Comment by CarlosEspinoTimon** [comment] 2023-01-15 08:32
Hi all!

Thank you very much for the fix, I'll try it right away :smile: 

I have one question related to this that is bothering me and maybe you could help me understand... isn't it pointless that Yahoo encrypts this AND shares the key to decrypt it? 

I mean, If I encrypt something it's because I want to secure the data and then I would share the key to whomever should be allowed to decrypt it, so, why encrypt and give the key. 

To me sound wrong, but probably I am missing something here :sweat_smile:

**Comment by bachan007** [comment] 2023-01-15 16:45
Also started facing the same issue, any solution here or do need to change the code structure?

**Comment by galashour** [comment] 2023-01-15 16:48
> Also started facing the same issue, any solution here or do need to change the code structure? TypeError: string indices must be integers

Double check you upgraded to the most recent version 0.2.4.

**Comment by bachan007** [comment] 2023-01-15 16:51
> 

Naah, using yfinance==0.1.93

**Comment by ValueRaider** [comment] 2023-01-15 16:52
Download latest PIP release to get the fix. That's how bug fixes work.

**Closed** 2023-01-15 16:53 UTC

**Comment by bachan007** [comment] 2023-01-15 16:59
> Download latest PIP release to get the fix. That's how bug fixes work.

still not working

**Comment by bachan007** [comment] 2023-01-15 17:06
> Also started facing the same issue, any solution here or do need to change the code structure? TypeError: string indices must be integers

I just upgraded the pip and yfinance, everything is working fine now.

**Comment by sarpvahabi** [comment] 2023-01-15 17:19
I had the same error for 2 days: TypeError: string indices must be integers
Now I upgraded it to 0.2.4 and it works fine while debugging but when I publish it via pyinstaller and run the exe, it gives the same error: TypeError: string indices must be integers

anyone has an idea? thanks

**Comment by bruce1095** [comment] 2023-01-15 23:43
It’s an issue with Pandas Datareader. Try this instead: #Use yahoo finance instead, it worked for me:import datetime as dt
import yfinance as yf

company = 'TATAELXSI.NS'

# Define a start date and End Date
start = dt.datetime(2020,1,1)
end =  dt.datetime(2022,1,1)

# Read Stock Price Data 
data = yf.download(company, start , end)

data.tail(10)Sent from my iPhoneOn Jan 15, 2023, at 9:19 AM, sarpvahabi ***@***.***> wrote:﻿
I had the same error for 2 days: TypeError: string indices must be integers
Now I upgraded it to 0.2.4 and it works fine while debugging but when I publish it via pyinstaller and run the exe, it gives the same error: TypeError: string indices must be integers
anyone has an idea? thanks

**Comment by no0be** [comment] 2023-01-16 13:08
Upgraded to yfinance==0.2.4 and it works fine now 👍 !

**Comment by havedill** [comment] 2023-01-18 15:52
> > Download latest PIP release to get the fix. That's how bug fixes work.
> 
> still not working

Did you use `pip install --upgrade yfinance`?

**Comment by JMKwins** [comment] 2023-01-19 21:14
Thx for the effort guys and girls. very much appreciated from here !

**Comment by driesdep** [comment] 2025-01-27 17:13
I have used TIINGO.com for getting the data : 

import os
from datetime import datetime 
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader.data as web

os.environ['API-Key']='dce859655570496eea6fd668f5fdef3c1ea312d6'
api_key = os.environ['API-Key']
spy_df = web.get_data_tiingo('SPY',start=datetime(2000,1,1),end=datetime(2021,1,1), api_key=api_key)

spy_df=spy_df.reset_index()
spy_df["date"] = pd.to_datetime(spy_df["date"])
spy_df["date"]=spy_df["date"].dt.strftime("%Y-%m-%d")
spy_df=spy_df.set_index("date")
spy_df=spy_df.drop("symbol",axis=1)
spy_df.index=pd.to_datetime(spy_df.index)
spy_df.head(10)

**Comment by CtoL95** [comment] 2025-01-27 19:40
@driesdep you shouldn't include your api-key for everyone to see.

**Comment by R5dan** [comment] 2025-01-27 20:07
Also, this is for a completely separate package.

**Comment by driesdep** [comment] 2025-01-28 09:20
ok, thanks
