### ISSUE TITLE
Problem with Monthly data - inconsistent dates. 

### ISSUE THREAD

**Issue by gcedism** [ranaroussi/yfinance#1205] opened 2022-11-26 23:04 UTC
Hi all, 
i am having a problem downloading monthly data for any tickers. The dates in the index of the result show more than just the beginning of the month. 

Example : 

```
import yfinance as yf
y_params = {
    'tickers': 'AAPL',
    'start': '2020-01-01',
    'end': '2022-11-01',
    'interval': '1mo'
}
data = yf.download(**y_params)['Adj Close']
```

The result I get for data is : 
```
Date
2020-01-01     75.805000
2020-02-01     66.951164
2020-02-07           NaN
2020-03-01     62.428360
2020-04-01     72.128082
2020-05-01     78.054482
2020-05-08           NaN
2020-06-01     89.801064
2020-07-01    104.630051
2020-08-01    127.060638
2020-08-07           NaN
2020-08-31           NaN
2020-09-01    114.239166
2020-10-01    107.383446
2020-11-01    117.435234
2020-11-06           NaN
2020-12-01    131.116058
2021-01-01    130.394714
2021-02-01    119.821625
2021-02-05           NaN
2021-03-01    120.881424
2021-04-01    130.094742
2021-05-01    123.315880
2021-05-07           NaN
2021-06-01    135.767838
2021-07-01    144.590378
2021-08-01    150.508408
2021-08-06           NaN
2021-09-01    140.478470
2021-10-01    148.718552
2021-11-01    164.106659
2021-11-05           NaN
2021-12-01    176.545380
2022-01-01    173.771454
2022-02-01    164.167221
2022-02-04           NaN
2022-03-01    173.823639
2022-04-01    156.940002
2022-05-01    148.169693
2022-05-06           NaN
2022-06-01    136.304245
2022-07-01    162.015808
2022-08-01    156.741913
2022-08-05           NaN
2022-09-01    137.971115
2022-10-01    153.086044
Name: Adj Close, dtype: float64
```
You see I have a lot of NaN for apparently random dates. 
Am I doing something wrong or this is a bug ?

Thank you in advance

**Comment by ValueRaider** [comment] 2022-11-27 00:39
This only happens when `actions=True`. Workaround: `y_params["actions"] = False`

The root cause is fixed in next release.

**Comment by gcedism** [comment] 2022-11-27 07:19
Thank you for the reply, but unfortunately it really doesn't work. Even if explicitly defining 'actions' = False, it gives the same result. 

It's understandable, given that in the definition of the **download** function, 'action' is already set to default False. 
_# multi.py_
```
def download(tickers, start=None, end=None, actions=False, threads=True, ignore_tz=True,
             group_by='column', auto_adjust=False, back_adjust=False, repair=False, keepna=False,
             progress=True, period="max", show_errors=True, interval="1d", prepost=False,
             proxy=None, rounding=False, timeout=10):
```

**Comment by gcedism** [comment] 2022-11-27 08:06
Found the bug : 

The cleaning of the lines on function **TickerBase.history** have to be run **after** dropping the Dividends and Splits columns : 

_# base.py_
_# TickerBase_
_# def history
```
if not actions:
            df.drop(columns=["Dividends", "Stock Splits"], inplace=True)

# duplicates and missing rows cleanup
df.dropna(how='all', inplace=True)
df = df[~df.index.duplicated(keep='first')]
```

**Comment by ValueRaider** [comment] 2022-11-27 12:39
I suspect you are running an old version, because latest release has reworked NaN handling. Run this:
```
import yfinance as yf
print(yf.__version__)
```
> '0.1.87'

**Comment by gcedism** [comment] 2022-11-27 21:56
Oh, you're right, I was running the 0.82, my bad! 
And I can see the fix ! Thank you very much for the help

**Closed** 2022-11-27 21:56 UTC
