### ISSUE TITLE
[Potential bug] checking intraday

### ISSUE THREAD

**Issue by xareelee** [ranaroussi/yfinance#1483] opened 2023-04-08 01:04 UTC
yfinance version: 0.2.14

I just review the source code. I found a potential bug.

In [multi.py#L87](https://github.com/ranaroussi/yfinance/blob/0.2.14/yfinance/multi.py#L87):

```py
        if interval[1:] in ['m', 'h']:
```

in [base.py#L755](https://github.com/ranaroussi/yfinance/blob/0.2.14/yfinance/base.py#L755) / base.py#788 / base.py#1297:

```py
intraday = interval[-1] in ("m", 'h')
```

The list slicings are different. If using `15m` for interval, for example, the results are different.

```py
intv = '15m'
print(intv[1:] in ['m', 'h'])  # False
print(intv[-1] in ['m', 'h'])  # True
```

It's better to implement a utils function to check that:

```py
# in utils.py
def isIntervalIntraday(interval):
    # You may want to check whether the interval string is valid, and raise an exception if invalid.
    # You may want to trim spaces before checking.
    return interval[-1] in ('m', 'h')

# in multi.py
    if utils.isIntervalIntraday(interval)

# in base.py
    intrady = utils.isIntervalIntraday(interval)
```

It's easier to write tests, and less bugs by calling the same pure function. It has benefit that if you want to add `s` for `second` timeframe in the future, you'll just need to change one line in the implementation.

----
This issue maybe is related to [base.py#632](https://github.com/ranaroussi/yfinance/blob/0.2.14/yfinance/base.py#L632):

```py
# 1) fix weired bug with Yahoo! - returning 60m for 30m bars
```

I'm not sure. I did not investigate this further.

**Comment by poudels** [comment] 2023-04-10 04:15
Agree with [xareelee]. There seems to be an issue with the 1m interval data. 

msft = yf.Ticker("MSFT")

hist = msft.history(interval="1m", period="7d") 
hist2 = msft.history(interval="1m", start="2023-03-29", end="2023-04-05")
print(len(hist), len(hist2))

Results below:

MSFT: No data found for this date range, symbol may be delisted
2728 0

**Comment by ValueRaider** [comment] 2023-04-10 09:33
@poudels No that's caused by #1478. The clue was: nothing to do with `interval`.

**Comment by steven9909** [comment] 2023-04-10 20:15
> Agree with [xareelee]. There seems to be an issue with the 1m interval data. Both the following should return similar data but trying to pass startdate and end date for 1m interval throws an error.
> 
> msft = yf.Ticker("MSFT")
> 
> hist = msft.history(interval="1m", period="7d") hist2 = msft.history(interval="1m", start="2023-03-29", end="2023-04-05") print(len(hist), len(hist2))
> 
> Results below:
> 
> MSFT: No data found for this date range, symbol may be delisted 2728 0

This issue is caused by https://github.com/ranaroussi/yfinance/issues/1268, specifying the end date will not return any data. It should be fixed by https://github.com/ranaroussi/yfinance/pull/1488.

**Closed** 2023-07-09 21:09 UTC
