### ISSUE TITLE
New yfinance==0.2.30 always gives 'string indices should be integer' even when fed datetime or string type date input 

### ISSUE THREAD

**Issue by Kanishkparganiha** [ranaroussi/yfinance#1706] opened 2023-09-29 04:19 UTC
### Describe bug

New yfinance==0.2.30 always gives 'string indices should be integer' even when fed datetime or string type date input 

### Simple code that reproduces your problem

import pandas
from pandas_datareader import data as pdr
import yfinance as yfin

yfin.pdr_override()

spy = pdr.get_data_yahoo('SPY', start='2022-10-24', end='2022-12-23')

print(spy)

[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['SPY']: OperationalError('unable to open database file')

### Debug log

['string](typeerror: string indices must be integer)

### `yfinance` version

yfinance==0.2.30

### Python version

yfinance==0.2.30

### Operating system

Ubuntu 22.04.3 LTS

**Comment by ValueRaider** [comment] 2023-09-29 09:55
Can you abandon `pandas_datareader` and use `yfinance` directly, then provide the full debug log because what I see isn't it.

**Comment by Kanishkparganiha** [comment] 2023-09-29 16:33
The issue resolve after I degraded the yfinance version to 'pip3 install yfinance==0.2.28'

**Comment by ValueRaider** [comment] 2023-09-29 17:00
That error should be fixed in 0.2.30.

**Comment by rickturner2001** [comment] 2023-09-29 19:14
@ValueRaider  this error occurs when the system cannot access the caching dir (I was able to reproduct this on an isolated readonly environment)

The current implementation in the dev dir works, you might want to push it to main (not the whole branch but that specific implementation)

**Closed** 2023-09-29 19:23 UTC

**Comment by Kanishkparganiha** [comment] 2023-09-29 20:29
Adding to that, I think the issue is resolved in the 0.2.30 version also as I uninstalled the 0.2.28 version and installed the 0.2.30 version, and no error was found
