### ISSUE TITLE
Info feature in yfinance has suddenly stopped working

### ISSUE THREAD

**Issue by ZaphodBeeblebrox12** [ranaroussi/yfinance#1296] opened 2023-01-14 05:21 UTC
### Version: 0.2.3 of yfinance Installed
- Info about your system:
  - Version: 0.2.3
  - Widnows 10 Home
  - Simple code that reproduces your problem
```
import yfinance as yf
pg = yf.Ticker('F')
sn = pg.info['shortName']
print(sn)

The following code produces TypeError
`TypeError: string indices must be integers`


This code was working yesterday however it has stopped working today. Could you please advise if this from Yahoo's end or my end?
Thanks

**Comment by mwip** [comment] 2023-01-14 10:08
Duplicate of #1291

**Closed** 2023-01-14 12:31 UTC
