### ISSUE TITLE
PYTHON DATA DOWNLOAD ERROR

### ISSUE THREAD

**Issue by federico999999** [ranaroussi/yfinance#1697] opened 2023-09-23 09:45 UTC
### Describe bug

Hi,
I am a student and am new in using python...
I use jupiter lab to do my analysis and when I try to download files directly from Yahoo Finance, python gives me the following error: 
1 Failed download:
['AAPL']: OperationalError('unable to open database file')

how can I solve it?
I thank you in advance

### Simple code that reproduces your problem

import yfinance as yf

ticker = 'AAPL'

interval = '1d'  

data = yf.download(ticker, period="1y", interval=interval)

data

### Debug log

[*********************100%%**********************]  1 of 1  completed

1 Failed download:
['AAPL']: OperationalError('unable to open database file')

### `yfinance` version

last

### Operating system

MAC

**Comment by janfrederik** [comment] 2023-09-23 10:05
This is a duplicate of #1694

**Closed** 2023-09-23 10:33 UTC
