### ISSUE TITLE
TickerBase.history should allow passing ints for start and end

### ISSUE THREAD

**Issue by srob1** [ranaroussi/yfinance#954] opened 2022-02-04 20:02 UTC
As currently implemented, `TickerBase.history()` allows passing only strs and datatimes for start and end, and uses `time.mktime()` to convert each of those to an integer timestamp.

This makes it impossible to retrieve quotes for dates that precede the start of the epoch, since `time.mktime()` will not convert dates that precede the epoch to negative timestamps.

Either the conversion from datetime to int should be done with `datetime.datetime.timestamp()`, which will convert dates preceding the start of the epoch to negative timestamps, or `TickerBase.history()` should allow passing an integer timestamp for start and end so that negative timestamps can be specified directly for dates that precede the start of the epoch.

For example, yahoo finance has quotes for IBM for 1962, but there is no way to pass a start date of 1/31/1962 to `TickerBase.history()` to retrieve a quote because time.mktime will raise OverflowError when trying to convert `datetime.datetime(1962, 1, 31, tzinfo=datetime.timezone.utc)`, and the same exception is raised when passing the date as the str '1962-01-31'.

So, for example, the following two two-line additions to `TickerBase.history()` in `yfinance\base.py` would allow the caller to specify the timestamps for start and end directly:

```
if start or period is None or period.lower() == "max":
	if start is None:
		start = -631159200
	elif isinstance(start, _datetime.datetime):
		start = int(_time.mktime(start.timetuple()))
        elif isinstance(start, int):                                                      <========
            pass                                                                          <========
	else:
		start = int(_time.mktime(
			_time.strptime(str(start), '%Y-%m-%d')))
	if end is None:
		end = int(_time.time())
	elif isinstance(end, _datetime.datetime):
		end = int(_time.mktime(end.timetuple()))
        elif isinstance(end, int):                                                        <========
            pass                                                                          <========
	else:
		end = int(_time.mktime(_time.strptime(str(end), '%Y-%m-%d')))

	params = {"period1": start, "period2": end}
else:
    ...
```

Then this call would work fine:

```
import datetime
import yfinance
start = int(datetime.datetime(1962, 1, 31, tzinfo=datetime.timezone.utc).timestamp())
end = start + 86400
data = yfinance.Ticker('IBM').history(start=start,end=end)

```

**Comment by PBbanana** [comment] 2022-07-12 22:19
Hi,

I second this suggestion. I have a similar problem caused by the current implementation of time.mktime(). This function assumes the input is in local time. This is a problem because often I want to set start/end times in the same time zone as the exchange, since this is how the data is returned. Stripping time zone info from my supplied start/end variables and changing that for local time creates a nightmare because retrieved data will depend on geographical location and time of the year (due to differences in daylight savings)

Thanks

**Comment by ValueRaider** [comment] 2022-07-12 22:33
I have a branch that fixes all this datetime/timezone stuff. But not merged in because I want volunteers to test it - I think it's bug-free, but changes are relatively substantial so scope for something to be broken.

If willing to volunteer here is my branch: https://github.com/ValueRaider/yfinance/tree/fix/timezone

Easiest to import direct without PIP:
```
import sys
sys.path.insert(0,"path/to/my/yfinance")
import yfinance as yf
print(yf) # Confirm you've loaded my fork
```

**Closed** 2023-01-06 21:46 UTC
